routes/web.php
Route::get('home', 'HomeController@index');
Route::post('home', ['as' => 'landingpage.contact', 'uses' => 'WelcomeController@sendContactForm']);

Route::group(array(), function() {
	#Authentication
	Route::get('/login', ['as' => 'login', 'uses' => 'SessionsController@create']);
	Route::get('/logout', ['as' => 'logout', 'uses' => 'SessionsController@destroy']);
	Route::resource('sessions', 'SessionsController', ['only' => ['create', 'store', 'destroy']]);
	Route::get('/changeActiveHostel/{id}', ['as' => 'changeactivehostel', 'uses' => 'SessionsController@changeActiveHostel']);

	#Registration
	Route::get('/register', ['as' => 'register', 'uses' => 'RegistrationController@create']);
	Route::post('/getTimezonesbyCountryID', ['as' => 'getTimezonesbyCountryID', 'uses' => 'RegistrationController@getTimezonesbyCountryID']);
	Route::resource('registration', 'RegistrationController', ['only' => ['create', 'store']]);

	#MyAllocatorCallback
	Route::post('/myallocator_callback', ['as' => 'myallocator.callback', 'uses' => 'MyAllocatorCallbackController@store']);

	#Uptime Page (This page is checked by pingdom and used to auto-switchover)
	Route::get('/uptimecheck', ['as' => 'uptimecheck', 'uses' => 'AjaxController@uptimeCheck']);

	#Testing Page
	Route::get('/testing', ['as' => 'testing', 'uses' => 'TestingController@index']);
	Route::post('/testing_add_guest', ['as' => 'testing.addGuest', 'uses' => 'TestingController@addGuest']);
	Route::post('/testing_add_booking', ['as' => 'testing.addBooking', 'uses' => 'TestingController@addBooking']);
	
});

Route::group(array('middleware' => 'auth'), function()
{
	#Calendar
	Route::get('/calendar', ['as' => 'calendar', 'uses' => 'CalendarController@create']);
	#legacy (can be removed soon):
	Route::get('/dashboard', ['as' => 'dashboard', 'uses' => 'CalendarController@create']);

	#Setup Steps
	Route::get('/setup', ['as' => 'setup.currentstep', 'uses' => 'SetupController@currentStep']);
	Route::get('/setup/next', ['as' => 'setup.nextstep', 'uses' => 'SetupController@nextStep']);
	Route::get('/setup/previous', ['as' => 'setup.previousstep', 'uses' => 'SetupController@previousStep']);

	#Calendar Test
	Route::get('/test', ['as' => 'testing.test', 'uses' => 'TestingController@testBookings']);
	Route::get('/test2', ['as' => 'testing.test2', 'uses' => 'TestingController@testPrivateBookingsImport']);

	#Ajax
	Route::post('/ajax/calendar', ['as' => 'ajax.calendar', 'uses' => 'AjaxController@calendar']);
	Route::get('/ajax/searchBookings', ['as' => 'ajax.searchBookings', 'uses' => 'AjaxController@searchBookings']);
	Route::post('/ajax/bookingDetails', ['as' => 'ajax.booking', 'uses' => 'AjaxController@bookingDetails']);
	Route::post('/ajax/getNotifications', ['as' => 'ajax.getnotifications', 'uses' => 'AjaxController@getNotifications']);

	Route::post('/savePayment', ['as' => 'savePayment', 'uses' => 'AjaxController@savePayment']);

	#Settings Page
	Route::get('/settings', ['as' => 'settings', 'uses' => 'SettingsController@index']);

	#MyAllocator callback setup
	Route::get('/set_myallocator_callback', ['as' => 'set.myallocator.callback', 'uses' => 'MyAllocatorCallbackController@setCallbackURL']);
	Route::get('/set_availability', ['as' => 'set.myallocator.availability', 'uses' => 'MyAllocatorCallbackController@setAvailability']);

	#Users Page
	Route::resource('users', 'UsersController', ['only' => ['index', 'show', 'store', 'destroy']]);

	#Guests Page
	Route::resource('guest', 'GuestController', ['only' => ['update']]);

	#Booking Page
	Route::resource('booking', 'BookingController', ['only' => ['show', 'update', 'edit', 'store', 'destroy']]);
	Route::post('/booking/{id}/updatelabel', ['as' => 'booking.updatelabel', 'uses' => 'BookingController@updateLabel']);
	Route::post('/booking/{id}/block', ['as' => 'booking.block', 'uses' => 'BookingController@block']);
	Route::post('/booking/{id}/unblock', ['as' => 'booking.unblock', 'uses' => 'BookingController@unblock']);
	Route::post('/booking/{id}/lock', ['as' => 'booking.lock', 'uses' => 'BookingController@lock']);
	Route::post('/booking/{id}/unlock', ['as' => 'booking.unlock', 'uses' => 'BookingController@unlock']);
	Route::post('/booking/{id}/noshow', ['as' => 'booking.noshow', 'uses' => 'BookingController@noshow']);
	Route::post('/booking/{id}/unallocate', ['as' => 'booking.unallocate', 'uses' => 'BookingController@unallocate']);
	Route::post('/booking/{id}/addStayToExistingTemp', ['as' => 'booking.addstaytoexistingtemp', 'uses' => 'BookingController@addStayToExistingTemp']);
	Route::post('/booking/{id}/movestay', ['as' => 'booking.movestay', 'uses' => 'BookingController@moveStay']);
	Route::post('/booking/createNewBookingAndBlock', ['as' => 'booking.createnewbookingandblock', 'uses' => 'BookingController@createNewBookingAndBlock']);
	Route::post('/booking/createNewBookingAndStay', ['as' => 'booking.createnewbookingandstay', 'uses' => 'BookingController@createNewBookingAndStay']);
	Route::resource('booking.note', 'NoteController', ['only' => ['index', 'store']]);

	#POS Page
	Route::resource('pos', 'POSController', ['only' => ['create']]);
	Route::get('/getProductsByCategoryId/{categoryId}', ['as' => 'pos.getProductsByCategoryId', 'uses' => 'POSController@getProductsByCategoryId']);
	Route::delete('/deleteItem/{id}', ['as' => 'pos.deleteitem', 'uses' => 'POSController@deleteItem']);
	Route::delete('/deletePayment/{id}', ['as' => 'pos.deletepayment', 'uses' => 'POSController@deletePayment']);

	#Invoice Page
	Route::get('/invoice/{id}/', ['as' => 'invoice.get', 'uses' => 'POSController@getInvoice']);

	#Expenses
	Route::resource('expense', 'ExpenseController', ['only' => ['index', 'store', 'destroy']]);

	#Reports
	Route::group(['prefix' => 'reports', 'as' => 'reports.'], function()
	{
		Route::get('/housekeeping', ['as' => 'housekeeping', 'uses' => 'ReportsController@houseKeeping']);
		Route::post('/housekeeping', ['as' => 'housekeepingdownload', 'uses' => 'ReportsController@houseKeeping']);
		Route::get('/paymentview', ['as' => 'paymentview', 'uses' => 'ReportsController@paymentView']);

		#DayView
		Route::get('/dayview', ['as' => 'dayview', 'uses' => 'ReportsController@dayView']);

		#Revenue
		Route::get('/revenue', ['as' => 'revenue', 'uses' => 'ReportsController@revenue']);

		#Dashboard
		Route::get('/dashboard', ['as' => 'dashboard', 'uses' => 'ReportsController@dashboard']);

		#Booking List
		Route::get('/bookinglist', ['as' => 'bookinglist', 'uses' => 'ReportsController@bookingList']);
		Route::get('/bookinglist/data', ['as' => 'bookinglistdata', 'uses' => 'ReportsController@bookingListData']);

		#PnL
		Route::get('/pnl', ['as' => 'profitandloss', 'uses' => 'ReportsController@pnl']);
		
		#M2m
		Route::get('/m2m', ['as' => 'month2month', 'uses' => 'ReportsController@m2m']);

		#Shift Reports
		Route::resource('shift', 'ShiftController', ['only' => ['index', 'create', 'store', 'show']]);

		#Shift Reports
		Route::resource('reviews', 'ReviewsController', ['only' => ['create', 'index', 'store', 'destroy']]);
	});

	#Settings
	Route::group(['prefix' => 'settings', 'as' => 'settings.'], function()
	{
		#Billing
		Route::resource('billing', 'BillingController', ['only' => ['create', 'store', 'destroy']]);

		#Room + Room Types Settings Page
		Route::get('/roomsOverview', ['as' => 'RoomsOverview', 'uses' => 'SettingsController@roomsOverview']);
		Route::resource('rooms', 'RoomsController', ['only' => ['edit', 'update', 'store', 'destroy']]);
		Route::post('/rooms/sort', ['as' => 'RoomsSort', 'uses' => 'RoomsController@sort']);
		Route::resource('roomtypes', 'RoomTypesController', ['only' => ['index', 'store', 'destroy']]);

		#POS Category + POS Product Settings Page
		Route::get('/POS', ['as' => 'posOverview', 'uses' => 'SettingsController@POSOverview']);
		Route::resource('POSCategory', 'POSCategoryController', ['only' => ['index', 'store', 'destroy', 'edit', 'update']]);
		Route::post('/POSCategory/sort', ['as' => 'POSCategory.sort', 'uses' => 'POSCategoryController@sort']);
		Route::resource('POSProduct', 'POSProductController', ['only' => ['index', 'store', 'destroy', 'edit', 'update']]);
		Route::post('/POSProduct/sort', ['as' => 'POSProduct.sort', 'uses' => 'POSProductController@sort']);

		#Money
		Route::resource('money', 'MoneyController', ['only' => ['create', 'store', 'destroy']]);

		#Money
		Route::get('/emailtest/{emailtype}', ['as' => 'email.test', 'uses' => 'EmailController@sendTestEmail']);
		Route::resource('email', 'EmailController', ['only' => ['create', 'store']]);

		#Payment Types
		Route::resource('paymenttypes', 'PaymentTypesController', ['only' => ['create', 'store', 'destroy']]);
		Route::post('/paymenttypes/sort', ['as' => 'paymenttypes.sort', 'uses' => 'PaymentTypesController@sort']);

		#Expenses
		Route::resource('expensecategory', 'ExpenseCategoryController', ['only' => ['create', 'store', 'destroy']]);

		#Rates
		Route::resource('rates', 'RatesController', ['only' => ['index', 'store', 'update', 'destroy']]);
		Route::get('/rates/competitor', ['as' => 'rates.competitor', 'uses' => 'RatesController@competitor']);
		Route::get('/rates/daily', ['as' => 'rates.daily', 'uses' => 'RatesController@daily']);
		Route::resource('competitor', 'CompetitorRatesController', ['only' => ['index', 'store', 'destroy']]);
		
		Route::post('/daily/store', ['as' => 'daily.store', 'uses' => 'DailyRatesController@store']);
		Route::post('/daily/get', ['as' => 'daily.get', 'uses' => 'DailyRatesController@get']);
		
		Route::get('/rates/discount', ['as' => 'rates.discount', 'uses' => 'RatesController@discount']);
		
		Route::post('/discount/find', ['as' => 'discount.find', 'uses' => 'DiscountRatesController@find']);
		Route::post('/discount/save', ['as' => 'discount.save', 'uses' => 'DiscountRatesController@save']);



		Route::get('/myallocator/resync', ['as' => 'myallocator.resync', 'uses' => 'MyAllocatorController@resync']);
		Route::resource('myallocator', 'MyAllocatorController', ['only' => ['create', 'store']]);
	});

resources/views/pages/reports/bookinglist.blade.php
@extends('layouts.backend')

@section('meta-title', 'HostelPro - Booking List Report')

@section('page-id', 'reports')

@section('content')

  @include('includes.reportssidebar')

  <div id="content-wrapper" class="m-t-md">

    <table id="booking-list-table" class="table table-striped" width="100%">
      <thead>
      <tr>
        <th>ID</th>
        <th>Date</th>
        <th>Status</th>
        <th>Last Name</th>
        <th>First Name</th>
        <th>Email</th>
        <th>Address</th>
        <th>Invoice #</th>
        <th>Country</th>
        <th>Passport Number</th>
        <th>Passport Country</th>
        <th>Place of Birth</th>
        <th>Passport Issued</th>
        <th>Passport Expired</th>
        <th># Guests</th>
        <th># Nights</th>
        <th>Actual $</th>
        <th>Commission</th>
        <th>Channel</th>
        <th>Created</th>
        <th>Updated</th>
      </tr>
      </thead>
      <tbody>

      </tbody>
      <tfoot>

      </tfoot>
    </table>

    <div id="custom-toolbar">
      <div class="input-group">
        <input id="booking-list-startdate" type="text" class="form-control input-sm datepicker" value="{{ $start }}">
        <span class="input-group-addon"><span class="fa fa-calendar"></span></span>
      </div>
      &nbsp; to &nbsp;
      <div class="input-group">
        <input id="booking-list-enddate" type="text" class="form-control input-sm datepicker" value="{{ $end }}">
        <span class="input-group-addon"><span class="fa fa-calendar"></span></span>
      </div>
      {!! Form::select('booking-list-status', $statuses, null, array('id' => 'booking-list-status', 'multiple' => 'multiple', 'size' => '1', 'class' => 'form-control')) !!}
      {!! Form::select('booking-list-channel', $channels, null, array('id' => 'booking-list-channel', 'multiple' => 'multiple', 'size' => '1', 'class' => 'form-control')) !!}
    </div>



    </div>
@endsection
@section('footer')
  @parent

  <script type="text/javascript">
    $(document).ready(function() {
      $('#booking-list-table').DataTable({
        processing: true,
        serverSide: true,
        stateSave: true,
        scrollX: true,
        dom: '<"#booking-list-top-buttons"B>l<"datatable-custom-toolbar">frtBip',
        order: [
          [19, "desc"]
        ],
        fixedHeader: true,
        ajax: {
          url: '{{ route('reports.bookinglistdata') }}',
          data: function (d) {
            d.startdate = $('#booking-list-startdate').val();
            d.enddate = $('#booking-list-enddate').val();
            d.channel = $('#booking-list-channel').val();
            d.status = $('#booking-list-status').val();
          }
        },
        columns: [
          {data: 'id', name: 'booking.id', searchable: false},
          {data: 'date', name: 'date', searchable: false},
          {data: 'status', name: 'booking.status', searchable: false},
          {data: 'lastname', name: 'guest.lastname', searchable: true},
          {data: 'firstname', name: 'guest.firstname', searchable: true},
          {data: 'email', name: 'guest.email', searchable: true, visible: false},
          {data: 'address_line_1', name: 'guest.address_line_1', searchable: true, visible: false},
          {data: 'invoice_number', name: 'guest.invoice_number', searchable: true, visible: false},
          {data: 'guestcountry', name: 'guestcountry', searchable: false, visible: false},
          {data: 'passport_number', name: 'guest.passport_number', searchable: true, visible: false},
          {data: 'passportcountry', name: 'passportcountry', searchable: false, visible: false},
          {data: 'place_of_birth', name: 'guest.place_of_birth', searchable: true, visible: false},
          {data: 'passport_issue_date', name: 'guest.passport_issue_date', searchable: true, visible: false},
          {data: 'passport_expiry_date', name: 'guest.passport_expiry_date', searchable: true, visible: false},
          {data: 'number_of_guests', name: 'number_of_guests', searchable: false},
          {data: 'nights', name: 'nights', searchable: false},
          {data: 'payment_actual', name: 'payment_actual', searchable: false},
          {data: 'commission_amount', name: 'commission_amount', searchable: false},
          {data: 'myallocator_channel_id', name: 'booking.myallocator_channel_id', searchable: false},
          {data: 'created_at', name: 'booking.created_at', searchable: false},
          {data: 'updated_at', name: 'booking.updated_at', searchable: false}

        ],
        buttons: [
          {
            extend: 'copyHtml5',
            className: 'btn btn-default',
            exportOptions: {
              columns: ':visible'
            }
          },
          {
            extend: 'pdfHtml5',
            exportOptions: {
              columns: ':visible'
            }
          },
          {
            extend: 'print',
            exportOptions: {
              columns: ':visible'
            }
          },
          {
            extend: 'csvHtml5',
            text: 'Excel',
            exportOptions: {
              columns: ':visible'
            }
          },
          'colvis'
        ],
        lengthMenu: [10, 25, 50, 100, 250, 1000],
        pageLength: 100,
        pagingType: "full_numbers"
      });

      $('#custom-toolbar').appendTo('div.datatable-custom-toolbar');

      $('.datepicker').datepicker({
        inline: true,
        showOtherMonths: true,
        dateFormat: "dd-mm-yyyy",
        dayNamesMin: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat']
      });

      $('#booking-list-startdate').on('change', function (e) {
        e.preventDefault();
        $('#booking-list-table').DataTable().draw();
      });

      $('#booking-list-enddate').on('change', function (e) {
        e.preventDefault();
        $('#booking-list-table').DataTable().draw();
      });

      $('#booking-list-status').on('change', function (e) {
        e.preventDefault();
        $('#booking-list-table').DataTable().draw();
      }).select2({
        placeholder: "Any Status"
      });

      $('#booking-list-channel').on('change', function (e) {
        e.preventDefault();
        $('#booking-list-table').DataTable().draw();
      }).select2({
        placeholder: "Any Channel"
      })


    });
  </script>

@endsection

resources/views/pages/reports/expenses.blade.php
@extends('layouts.backend')

@section('meta-title', 'HostelPro - Revenue Report')

@section('page-id', 'reports')

@section('content')

    <div class="row m-t-md">
        <div class="col-lg-12">
            @include('partials.daterangepicker-inline')
        </div>
    </div>

    @include('includes.reportssidebar')

    <div id="content-wrapper" class="m-t-md">

        <div class="row">
            <div class="col-sm-12">

                <table class="table table-condensed dayView" id="expenseTable">
                    <thead>
                    <tr>
                        <th>Date</th>
                        <th>Category</th>
                        <th>Expense</th>
                        <th>Amount</th>
                        <th>Added By</th>
                        <th>Added At</th>
                        <th>Delete</th>
                    </tr>
                    </thead>
                    <tbody>
                    @forelse($expenses as $expense)
                        <tr id="{{ $expense['id'] }}">
                            <td>{{ $expense['date'] }}</td>
                            <td>{{ $expense['category'] }}</td>
                            <td>{{ $expense['name'] }}</td>
                            <td>{{ $expense->prettyPrice }}</td>
                            <td>{{ $expense->user->fullName() }}</td>
                            <td>{{ $expense['created_at'] }}</td>
                            <td>
                                <button class="btn btn-xs btn-danger deleteExpense"
                                        data-expenseid="{{ $expense['id'] }}"><i class="fa fa-trash-o"></i>&nbsp; Delete
                                </button>
                            </td>
                        </tr>
                    @empty
                        <tr>
                            <td colspan="7">There are no expenses for the dates you specified.</td>
                        </tr>
                    @endforelse

                    </tbody>
                </table>


            </div>
        </div>
        <div class="row">
            <div class="col-sm-12">
                @include('partials.addexpense')
            </div>
        </div>


    </div>
@endsection
@section('footer')
    @parent

    <script type="text/javascript">
        $(document).ready(function () {

            $(document).on('click', '.deleteExpense', function () {
                confirmDeletePopup('{!! route('expense.destroy', '') !!}', $(this).data("expenseid"), 'DELETE');
            });

            function confirmDeletePopup($type, $id, $requesttype) {
                noty({
                    text: 'Are you sure you want to delete this item?',
                    theme: 'relax',
                    layout: 'center',
                    modal: true,
                    animation: {
                        open: {height: 'toggle'}, // jQuery animate function property object
                        close: {height: 'toggle'}, // jQuery animate function property object
                        easing: 'swing', // easing
                        speed: 150 // opening & closing animation speed
                    },
                    buttons: [
                        {
                            addClass: 'btn btn-success', text: 'Ok', onClick: function ($noty) {
                            $noty.close();
                            deleteItem($type, $id, $requesttype);
                        }
                        },
                        {
                            addClass: 'btn btn-danger', text: 'Cancel', onClick: function ($noty) {
                            $noty.close();
                        }
                        }
                    ]
                });
            };

            function deleteItem($type, $id, $requesttype) {
                $.ajax({
                    url: $type + "/" + $id,
                    type: $requesttype,
                    success: function (response) {
                        var tr = $("#" + $id);
                        tr.css("background-color", "#EF5C5C");
                        tr.fadeOut(400, function () {
                            tr.remove();
                        });
                    },
                    error: function (xhr, ajaxOptions, thrownError) {
                        createErrorModal(xhr.responseText);
                    }
                });
            };

        });
    </script>

@endsection

resources/views/pages/reports/housekeeping.blade.php
@extends('layouts.backend')

@section('meta-title', 'HostelPro - HouseKeeping')

@section('page-id', 'reports')

@section('content')

    <div class="row hidden-print m-t-md">
        <div class="col-sm-12">

            {!! Form::open(['route' => 'reports.housekeepingdownload', 'class' => 'form-inline', 'id' => 'housekeeping-form', 'method' => 'GET']) !!}
            <div class="input-group">
                <input id="datepicker-housekeeping" name="date" type="text"
                       class="form-control input-sm" value="{{ $date }}">
                <span class="input-group-addon"><span class="fa fa-calendar"></span></span>
            </div>
            <div class="input-group">
                <button class="btn btn-info" id="printButton">Print</button>
            </div>
            {!! Form::close() !!}

        </div>
    </div>


    @include('includes.reportssidebar')

    <div id="content-wrapper" class="m-t-md">

        <h1 class="text-center">Housekeeping for {{ Auth::user()->currenthostel->name }}</h1>

        <h3 class="text-center">{{ $report->formatted_date }}</h3>

        <table width="100%" class="table table-condensed m-t-lg">
            <thead>
            <tr>
                <th width="35%">Room</th>
                <th width="7%" class="text-center">Arr</th>
                <th width="7%" class="text-center">Dep</th>
                <th width="7%" class="text-center">Rem</th>
                <th width="7%" class="text-center">NiU</th>
                <th width="7%" class="text-center">Free</th>
                <th width="30%" class="text-center">Notes</th>
            </tr>
            </thead>
            <tbody>
            @foreach ($report->rooms as $room)
                <tr>
                    <td>{{ $room->name }}</td>
                    <td class="text-center">{{ $report->data[$room->id]['arr'] }}</td>
                    <td class="text-center">{{ $report->data[$room->id]['dep'] }}</td>
                    <td class="text-center">{{ $report->data[$room->id]['rem'] }}</td>
                    <td class="text-center">{{ $report->data[$room->id]['niu'] }}</td>
                    <td class="text-center">{{ $report->data[$room->id]['free'] }}</td>
                    <td></td>
                </tr>
            @endforeach
            </tbody>
        </table>

        <p class="text-center">Arr = Arrivals, Dep = Departures, Rem = Remainings, NiU = Not in Use or
            Blocked</p>

        <table class="table table-condensed">
            <thead>
            <tr>
                <th colspan="5">
                    <h4>
                        Departing
                        @if ($dayreport->totals['departing'] > 0)
                            / <span class="smallerfont"> {{ $dayreport->totals['departing'] }} Guests</span>
                        @endif
                    </h4>
                </th>
            </tr>
            <tr>
                <th width="20%">Name</th>
                <th width="20%">Status</th>
                <th width="20%">Room</th>
                <th width="20%">Bed</th>
                <th width="20%"># Guests</th>
            </tr>
            </thead>
            <tbody>
            @forelse($dayreport->departing as $departing)
                @if ($departing->status == "Checked Out")
                    <tr class="checkedout">
                @else
                    <tr>
                        @endif
                        <td><a href="#" class="loadBooking" data-bookingid="{{ $departing->id }}">{{ $departing->id }}
                                - {{ $departing->lastname }}</a></td>
                        <td>{{ $departing->status }}</td>
                        <td>{{ $departing->room_name }}</td>
                        <td>{{ $departing->bed }}</td>
                        <td>{{ $departing->number_of_guests }}</td>
                    </tr>
                    @empty
                        <tr>
                            <td colspan="5">No bookings are departing on this day.</td>
                        </tr>
                    @endforelse
            </tbody>
        </table>

        <table class="table table-condensed">
            <thead>
            <tr>
                <th colspan="5">
                    <h4>
                        Changing Rooms
                        @if ($dayreport->totals['changing_rooms'] > 0)
                            / <span class="smallerfont"> {{ $dayreport->totals['changing_rooms'] }} Guests</span>
                        @endif
                    </h4>
                </th>
            </tr>
            <tr>
                <th width="20%">Name</th>
                <th width="20%">Status</th>
                <th width="20%">Room</th>
                <th width="20%">Bed</th>
                <th width="20%"># Guests</th>
            </tr>
            </thead>
            <tbody>
            @forelse($dayreport->changing_rooms as $changing)
                @if ($changing->status == "Checked Out")
                    <tr class="checkedout">
                @else
                    <tr>
                        @endif
                        <td><a href="#" class="loadBooking" data-bookingid="{{ $changing->id }}">{{ $changing->id }}
                                - {{ $changing->lastname }}</a></td>
                        <td>{{ $changing->status }}</td>
                        <td>{{ $changing->room_name }}</td>
                        <td>{{ $changing->bed }}</td>
                        <td>{{ $changing->number_of_guests }}</td>
                    </tr>
                    @empty
                        <tr>
                            <td colspan="5">No bookings are changing rooms on this day.</td>
                        </tr>
                    @endforelse
            </tbody>
        </table>

    </div>

@endsection
@section('footer')
    @parent

    <script type="text/javascript">
        $(function () {
            $('#datepicker-housekeeping').datepicker({
                inline: true,
                showOtherMonths: true,
                dateFormat: "dd-mm-yy",
                dayNamesMin: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
                onSelect: function () {
                    $(this).closest('form').submit();
                }
            });
            //Generate a new date
            var date = new Date();
            //Set the datepicker to the date we just generated
            $('#datepicker-houseKeeping').datepicker("setDate", date);
        });

        $('#printButton').click(function () {
            window.print();
        });
    </script>

@endsection

resources/views/pages/reports/reviews.blade.php
@extends('layouts.backend')

@section('meta-title', 'HostelPro - Revenue Report')

@section('page-id', 'reports')

@section('content')

    @include('includes.reportssidebar')

    <div id="content-wrapper" class="m-t-md">


        <div class="row">

            <div class="col-md-6 col-lg-8">
                @if (Auth::user()->currenthostel->reviewURLs->count() == 0)
                    <p><strong>You have not yet added any review URLs</strong></p>
                @endif
                <p>HostelPro can track reviews from Booking.com, HostelWorld and
                    HostelBookers.</p>

                <p>To make use of this functionality you will first need to tell HostelPro the
                    URL to your hostel</p>

                <p>You can find the URL by going to Booking.com, HostelWorld or HostelBookers,
                    loading your public hostel page and then copying and pasting the URL in the
                    form.</p>

                <p>You only need to do this once, then HostelPro will automatically check for
                    new reviews every single day.</p>

                <p><strong>Green</strong> means a URL is already added, <strong>red</strong>
                    means a url is not yet added.</p>
            </div>
        </div>

        <div class="row">
            <div class="col-xs-12">

                @foreach ($reviews as $review)
                    <div class="panel review">
                        <div class="panel-heading">

                            <label class="label label-lg {{ $review->overall_score >= 75 ? 'bg-success' : ($review->overall_score >= 50 ? 'bg-warning' : 'bg-danger') }}">{{ $review->overall_score }}</label>

                            {{ $review->url->channel->name }}
                        </div>

                        <div class="panel-body">
                            @if ((!$review->liked) && (!$review->disliked) && (!$review->overall))
                                <small class="text-muted">No text written.</small>
                            @endif
                            @if ($review->overall)
                                <p>{{ $review->overall }}</p>
                            @endif
                            @if ($review->liked)
                                <p>
                                    <strong>Positive: </strong>{{ $review->liked }}
                                </p>
                            @endif
                            @if ($review->disliked)
                                <p>
                                    <strong>Negative:</strong>
                                    {{ $review->disliked }}
                                </p>
                            @endif
                        </div>

                        @if ($review->value_score)
                            <div class="panel-footer small">
                                <p>
                                    Atmosphere: <strong>{{ $review->atmosphere_score }}</strong>&nbsp;&nbsp;
                                    Cleanliness: <strong>{{ $review->cleanliness_score }}</strong>&nbsp;&nbsp;
                                    Facilities: <strong>{{ $review->facilities_score }}</strong>&nbsp;&nbsp;
                                    Location: <strong>{{ $review->location_score }}</strong>&nbsp;&nbsp;
                                    Safety: <strong>{{ $review->safety_score }}</strong>&nbsp;&nbsp;
                                    Staff: <strong>{{ $review->staff_score }}</strong>&nbsp;&nbsp;
                                    Value: <strong>{{ $review->value_score }}</strong>&nbsp;&nbsp;
                                </p>
                            </div>
                        @endif
                    </div>

                @endforeach
            </div>
        </div>


    </div>
@endsection