routes/web.php
Route::get('home', 'HomeController@index');
Route::post('home', ['as' => 'landingpage.contact', 'uses' => 'WelcomeController@sendContactForm']);

Route::group(array(), function() {
	#Authentication
	Route::get('/login', ['as' => 'login', 'uses' => 'SessionsController@create']);
	Route::get('/logout', ['as' => 'logout', 'uses' => 'SessionsController@destroy']);
	Route::resource('sessions', 'SessionsController', ['only' => ['create', 'store', 'destroy']]);
	Route::get('/changeActiveHostel/{id}', ['as' => 'changeactivehostel', 'uses' => 'SessionsController@changeActiveHostel']);

	#Registration
	Route::get('/register', ['as' => 'register', 'uses' => 'RegistrationController@create']);
	Route::post('/getTimezonesbyCountryID', ['as' => 'getTimezonesbyCountryID', 'uses' => 'RegistrationController@getTimezonesbyCountryID']);
	Route::resource('registration', 'RegistrationController', ['only' => ['create', 'store']]);

	#MyAllocatorCallback
	Route::post('/myallocator_callback', ['as' => 'myallocator.callback', 'uses' => 'MyAllocatorCallbackController@store']);

	#Uptime Page (This page is checked by pingdom and used to auto-switchover)
	Route::get('/uptimecheck', ['as' => 'uptimecheck', 'uses' => 'AjaxController@uptimeCheck']);

	#Testing Page
	Route::get('/testing', ['as' => 'testing', 'uses' => 'TestingController@index']);
	Route::post('/testing_add_guest', ['as' => 'testing.addGuest', 'uses' => 'TestingController@addGuest']);
	Route::post('/testing_add_booking', ['as' => 'testing.addBooking', 'uses' => 'TestingController@addBooking']);
	
});

Route::group(array('middleware' => 'auth'), function()
{
	#Calendar
	Route::get('/calendar', ['as' => 'calendar', 'uses' => 'CalendarController@create']);
	#legacy (can be removed soon):
	Route::get('/dashboard', ['as' => 'dashboard', 'uses' => 'CalendarController@create']);

	#Setup Steps
	Route::get('/setup', ['as' => 'setup.currentstep', 'uses' => 'SetupController@currentStep']);
	Route::get('/setup/next', ['as' => 'setup.nextstep', 'uses' => 'SetupController@nextStep']);
	Route::get('/setup/previous', ['as' => 'setup.previousstep', 'uses' => 'SetupController@previousStep']);

	#Calendar Test
	Route::get('/test', ['as' => 'testing.test', 'uses' => 'TestingController@testBookings']);
	Route::get('/test2', ['as' => 'testing.test2', 'uses' => 'TestingController@testPrivateBookingsImport']);

	#Ajax
	Route::post('/ajax/calendar', ['as' => 'ajax.calendar', 'uses' => 'AjaxController@calendar']);
	Route::get('/ajax/searchBookings', ['as' => 'ajax.searchBookings', 'uses' => 'AjaxController@searchBookings']);
	Route::post('/ajax/bookingDetails', ['as' => 'ajax.booking', 'uses' => 'AjaxController@bookingDetails']);
	Route::post('/ajax/getNotifications', ['as' => 'ajax.getnotifications', 'uses' => 'AjaxController@getNotifications']);

	Route::post('/savePayment', ['as' => 'savePayment', 'uses' => 'AjaxController@savePayment']);

	#Settings Page
	Route::get('/settings', ['as' => 'settings', 'uses' => 'SettingsController@index']);

	#MyAllocator callback setup
	Route::get('/set_myallocator_callback', ['as' => 'set.myallocator.callback', 'uses' => 'MyAllocatorCallbackController@setCallbackURL']);
	Route::get('/set_availability', ['as' => 'set.myallocator.availability', 'uses' => 'MyAllocatorCallbackController@setAvailability']);

	#Users Page
	Route::resource('users', 'UsersController', ['only' => ['index', 'show', 'store', 'destroy']]);

	#Guests Page
	Route::resource('guest', 'GuestController', ['only' => ['update']]);

	#Booking Page
	Route::resource('booking', 'BookingController', ['only' => ['show', 'update', 'edit', 'store', 'destroy']]);
	Route::post('/booking/{id}/updatelabel', ['as' => 'booking.updatelabel', 'uses' => 'BookingController@updateLabel']);
	Route::post('/booking/{id}/block', ['as' => 'booking.block', 'uses' => 'BookingController@block']);
	Route::post('/booking/{id}/unblock', ['as' => 'booking.unblock', 'uses' => 'BookingController@unblock']);
	Route::post('/booking/{id}/lock', ['as' => 'booking.lock', 'uses' => 'BookingController@lock']);
	Route::post('/booking/{id}/unlock', ['as' => 'booking.unlock', 'uses' => 'BookingController@unlock']);
	Route::post('/booking/{id}/noshow', ['as' => 'booking.noshow', 'uses' => 'BookingController@noshow']);
	Route::post('/booking/{id}/unallocate', ['as' => 'booking.unallocate', 'uses' => 'BookingController@unallocate']);
	Route::post('/booking/{id}/addStayToExistingTemp', ['as' => 'booking.addstaytoexistingtemp', 'uses' => 'BookingController@addStayToExistingTemp']);
	Route::post('/booking/{id}/movestay', ['as' => 'booking.movestay', 'uses' => 'BookingController@moveStay']);
	Route::post('/booking/createNewBookingAndBlock', ['as' => 'booking.createnewbookingandblock', 'uses' => 'BookingController@createNewBookingAndBlock']);
	Route::post('/booking/createNewBookingAndStay', ['as' => 'booking.createnewbookingandstay', 'uses' => 'BookingController@createNewBookingAndStay']);
	Route::resource('booking.note', 'NoteController', ['only' => ['index', 'store']]);

	#POS Page
	Route::resource('pos', 'POSController', ['only' => ['create']]);
	Route::get('/getProductsByCategoryId/{categoryId}', ['as' => 'pos.getProductsByCategoryId', 'uses' => 'POSController@getProductsByCategoryId']);
	Route::delete('/deleteItem/{id}', ['as' => 'pos.deleteitem', 'uses' => 'POSController@deleteItem']);
	Route::delete('/deletePayment/{id}', ['as' => 'pos.deletepayment', 'uses' => 'POSController@deletePayment']);

	#Invoice Page
	Route::get('/invoice/{id}/', ['as' => 'invoice.get', 'uses' => 'POSController@getInvoice']);

	#Expenses
	Route::resource('expense', 'ExpenseController', ['only' => ['index', 'store', 'destroy']]);

	#Reports
	Route::group(['prefix' => 'reports', 'as' => 'reports.'], function()
	{
		Route::get('/housekeeping', ['as' => 'housekeeping', 'uses' => 'ReportsController@houseKeeping']);
		Route::post('/housekeeping', ['as' => 'housekeepingdownload', 'uses' => 'ReportsController@houseKeeping']);
		Route::get('/paymentview', ['as' => 'paymentview', 'uses' => 'ReportsController@paymentView']);

		#DayView
		Route::get('/dayview', ['as' => 'dayview', 'uses' => 'ReportsController@dayView']);

		#Revenue
		Route::get('/revenue', ['as' => 'revenue', 'uses' => 'ReportsController@revenue']);

		#Dashboard
		Route::get('/dashboard', ['as' => 'dashboard', 'uses' => 'ReportsController@dashboard']);

		#Booking List
		Route::get('/bookinglist', ['as' => 'bookinglist', 'uses' => 'ReportsController@bookingList']);
		Route::get('/bookinglist/data', ['as' => 'bookinglistdata', 'uses' => 'ReportsController@bookingListData']);

		#PnL
		Route::get('/pnl', ['as' => 'profitandloss', 'uses' => 'ReportsController@pnl']);
		
		#M2m
		Route::get('/m2m', ['as' => 'month2month', 'uses' => 'ReportsController@m2m']);

		#Shift Reports
		Route::resource('shift', 'ShiftController', ['only' => ['index', 'create', 'store', 'show']]);

		#Shift Reports
		Route::resource('reviews', 'ReviewsController', ['only' => ['create', 'index', 'store', 'destroy']]);
	});

	#Settings
	Route::group(['prefix' => 'settings', 'as' => 'settings.'], function()
	{
		#Billing
		Route::resource('billing', 'BillingController', ['only' => ['create', 'store', 'destroy']]);

		#Room + Room Types Settings Page
		Route::get('/roomsOverview', ['as' => 'RoomsOverview', 'uses' => 'SettingsController@roomsOverview']);
		Route::resource('rooms', 'RoomsController', ['only' => ['edit', 'update', 'store', 'destroy']]);
		Route::post('/rooms/sort', ['as' => 'RoomsSort', 'uses' => 'RoomsController@sort']);
		Route::resource('roomtypes', 'RoomTypesController', ['only' => ['index', 'store', 'destroy']]);

		#POS Category + POS Product Settings Page
		Route::get('/POS', ['as' => 'posOverview', 'uses' => 'SettingsController@POSOverview']);
		Route::resource('POSCategory', 'POSCategoryController', ['only' => ['index', 'store', 'destroy', 'edit', 'update']]);
		Route::post('/POSCategory/sort', ['as' => 'POSCategory.sort', 'uses' => 'POSCategoryController@sort']);
		Route::resource('POSProduct', 'POSProductController', ['only' => ['index', 'store', 'destroy', 'edit', 'update']]);
		Route::post('/POSProduct/sort', ['as' => 'POSProduct.sort', 'uses' => 'POSProductController@sort']);

		#Money
		Route::resource('money', 'MoneyController', ['only' => ['create', 'store', 'destroy']]);

		#Money
		Route::get('/emailtest/{emailtype}', ['as' => 'email.test', 'uses' => 'EmailController@sendTestEmail']);
		Route::resource('email', 'EmailController', ['only' => ['create', 'store']]);

		#Payment Types
		Route::resource('paymenttypes', 'PaymentTypesController', ['only' => ['create', 'store', 'destroy']]);
		Route::post('/paymenttypes/sort', ['as' => 'paymenttypes.sort', 'uses' => 'PaymentTypesController@sort']);

		#Expenses
		Route::resource('expensecategory', 'ExpenseCategoryController', ['only' => ['create', 'store', 'destroy']]);

		#Rates
		Route::resource('rates', 'RatesController', ['only' => ['index', 'store', 'update', 'destroy']]);
		Route::get('/rates/competitor', ['as' => 'rates.competitor', 'uses' => 'RatesController@competitor']);
		Route::get('/rates/daily', ['as' => 'rates.daily', 'uses' => 'RatesController@daily']);
		Route::resource('competitor', 'CompetitorRatesController', ['only' => ['index', 'store', 'destroy']]);
		
		Route::post('/daily/store', ['as' => 'daily.store', 'uses' => 'DailyRatesController@store']);
		Route::post('/daily/get', ['as' => 'daily.get', 'uses' => 'DailyRatesController@get']);
		
		Route::get('/rates/discount', ['as' => 'rates.discount', 'uses' => 'RatesController@discount']);
		
		Route::post('/discount/find', ['as' => 'discount.find', 'uses' => 'DiscountRatesController@find']);
		Route::post('/discount/save', ['as' => 'discount.save', 'uses' => 'DiscountRatesController@save']);



		Route::get('/myallocator/resync', ['as' => 'myallocator.resync', 'uses' => 'MyAllocatorController@resync']);
		Route::resource('myallocator', 'MyAllocatorController', ['only' => ['create', 'store']]);
	});

resources/views/pages/rates/competitorrates.blade.php
@extends('layouts.backend')

@section('meta-title', 'HostelPro - Settings')

@section('page-id', 'rates')

@section('content')

    @include('includes.ratessidebar')

    <div id="content-wrapper" class="m-t-md">


        <div class="row seasonRates">
            <ul class="nav nav-tabs">
                @foreach($rates->room_types as $key => $room_type)
                    <li class="{{ ($key == 0) ? 'active' : '' }}">
                        <a href="">{{ $room_type->name }}</a>
                    </li>
                @endforeach
            </ul>

            <div class="tab-content col-sm-10">

                @foreach($rates->room_types as $key => $room_type)
                    <div class="tab-pane {{ ($key == 0) ? 'active' : ''}}">
                        <table class="table table-striped table-condensed">

                            @foreach ($rates->calendar as $i => $week)
                                <thead>
                                <tr>
                                    <th></th>
                                    @foreach ($week as $date)
                                        <th>{!! $i == 0 ? $date->format('D'). '<br>' : '' !!} {{ $date->format('d M Y') }}</th>
                                    @endforeach
                                </tr>
                                </thead>
                                <tbody>
                                <tr>
                                    <td><strong>{{ Auth::user()->currenthostel->name }}</strong></td>
                                    @foreach ($week as $date)
                                        <td>{{ $calendar->availability[$key]['rates'][$date->toDateString()]['price'] ?? null }}</td>
                                    @endforeach
                                </tr>

                                @foreach ($rates->competitor_urls as $competitor_url )
                                    <tr>
                                        <td><strong>{{ $competitor_url->name }}</strong></td>
                                        @foreach ($week as $date)
                                            <td>{{ $rates->rates[$room_type->id][$competitor_url->id][$date->toDateString()] ?? null }}</td>
                                        @endforeach
                                    </tr>
                                @endforeach
                                </tbody>
                            @endforeach

                        </table>
                    </div>
                @endforeach
            </div>


        </div>


    </div>
@endsection
@section('footer')
    @parent
    <script type="text/javascript">
        $(document).ready(function (event) {
            $('.seasonRates').on('click', '.nav-tabs li', function (event) {
                event.preventDefault();
                $('.nav-tabs li').removeClass('active');
                $(this).addClass('active');
                $(this).closest('.seasonRates').find('.tab-pane').removeClass('active').eq($(this).index()).addClass('active');
            });

//            $('.nav-tabs')
//                    .scrollingTabs({
//                        scrollToTabEdge: true,
//                        disableScrollArrowsOnFullyScrolled: true
//                    })
//                    .on('ready.scrtabs', function () {
//                        $('.tab-content').show();
//                        var width = $('.report-right').width() - 40;
//                        $('.scrtabs-tabs-fixed-container').width(width);
//                    });

        });
    </script>
@endsection

resources/views/pages/rates/dailyrates.blade.php
@extends('layouts.backend')

@section('meta-title', 'HostelPro - Daily Rates')

@section('page-id', 'rates')

@section('content')


    @include('includes.ratessidebar')

    <div class="row">
        <div class="main-content col-lg-10 col-md-9">

            <div class="daily-date">
                <button class="btn btn-success btn-today">Today</button>
                <input class="date" type="text" value="{{ array_keys($datesFormatted)[0] }}"/>
            </div>

            <div class="daily-pricing">
                <h2>Daily Pricing</h2>
                <table class="pricing-table table-responsive">
                    <thead>
                    <th></th>
                    @php $day = 0; @endphp
                    @foreach ($datesFormatted as $key => $data)
                        <th>
                            <div class="day-week day{{$day}}">{{$data['dayOfWeek']}}</div>
                            <div class="date-week date{{$day}}">{{$data['day']}}</div>
                        </th>@php ++$day; @endphp
                    @endforeach
                    </thead>
                    <tbody>
                    @foreach ($occupancies as $roomname => $data)
                        <tr>
                            <td class="first-cell">
                                <div class="top-half">{{$roomname}}</div>
                                <div class="bottom-half">Available</div>
                            </td>
                            @php $day = 0; @endphp
                            @foreach ($data as $date => $value)
                                <td class="{{$value['color']}}-cell" id="roomtype{{$roomTypes[$roomname]}}-{{$day}}">
                                    <div class="top-half rate"
                                         data-roomtype="{{$roomTypes[$roomname]}}"
                                         data-date="{{$date}}"
                                         contenteditable="true">{{$value['rate']}}</div>
                                    <div class="bottom-half">{{$value['available']}}</div>
                                </td>
                                @php ++$day; @endphp
                            @endforeach
                        </tr>
                    @endforeach
                    </tbody>
                </table>
                <div class="form-group pull-right">
                    <button class="form-submit btn btn-success">
                        <img src="/assets/images/i-save.png"/>&nbsp;&nbsp;Save Rates
                    </button>
                </div>
            </div>

        </div>
    </div>
@endsection
@section('footer')
    @parent
    <script type="text/javascript">
        $(document).ready(function (event) {
            var dateToday = new Date();
            $("input.date").datepicker({
                dateFormat: "yy-mm-dd",
                numberOfMonths: 3,
                minDate: dateToday
            }).on("change", function (e) {
                updateTable();
            });

            function updateTable(){
                var datePicker = $('input.date');
                var startDate = datePicker.val();

                var currentDate = datePicker.datepicker( 'getDate' );
                updateHeader(currentDate);

                $.ajax({
                    type: "POST",
                    url: '{{route('settings.daily.get')}}',
                    data: {startDate:startDate},
                    success: function (res) {
                        var items = res.items;
                        for(var key in items)
                        {
                            //key is ID of roomtype
                            //value is array with rate data
                            let value = items[key];

                            for(var i=0; i<value.length; i++)
                            {
                                var data = value[i];

                                var cellId = '#roomtype'+key+'-'+i;

                                var cell = $(cellId);

                                cell.html(
                                    "<div class='top-half rate' data-roomtype='"+key+
                                    "' data-date='"+data.date+"' contenteditable='true'>"+
                                    data.rate+"</div><div class='bottom-half'>"+data.available+"</div>"
                                );
                                cell.attr('class','');
                                cell.addClass('cell-'+data.color);
                            }
                        }
                    }
                })
            }

            function updateHeader(startDate)
            {
                for(var i=0; i< 7; i++)
                {
                    var day = getDayOfWeek(startDate.getDay());
                    var date = startDate.getDate();

                    //update th values
                    $('.day'+i).html(day);
                    $('.date'+i).html(date);

                    //jump to next day
                    var ms = startDate.getTime() + 86400000;
                    startDate = new Date(ms);
                }
            }

            function getDayOfWeek(index)
            {
                var weekday = new Array(7);
                weekday[0] =  "Sun";
                weekday[1] = "Mon";
                weekday[2] = "Tue";
                weekday[3] = "Wed";
                weekday[4] = "Thu";
                weekday[5] = "Fri";
                weekday[6] = "Sat";

                return weekday[index];
            }

            $('.btn-today').on('click', function(e){
                $("input.date").datepicker("setDate", dateToday);
                updateTable();
            });

            //save daily rates
            $('.form-submit').on('click', function(){
                var items = $( ".rate-changed" );

                var rates = [];

                items.each(function() {
                    var rate = $( this ).html();
                    var date = $( this ).data('date');
                    var roomtype = $( this ).data('roomtype');

                    var obj = [roomtype, date, rate];
                    rates.push(obj);
                });

                var start = $("input.date").val();

                $.ajax({
                    type: "POST",
                    url: '{{route('settings.daily.store')}}',
                    data: {rates:rates,start:start},
                    success: function (res) {

                        var msg = res.message;
                        createSuccessModal(msg+". MyAllocator users please allow a few minutes for this to reach booking channels.");

                        $('.pricing-table .top-half[contenteditable=true]').removeClass('rate-changed');

                    }
            })});

            /*********************************/

            /* Editable Prices - Daily Rates */
            $(document).on('keyup', '.pricing-table .top-half[contenteditable=true]', function () {
                $( this ).addClass('rate-changed');

                var limit = 10;
                var minlimit = 1;
                var text = $(this).html();
                var chars = text.length;
                if (chars >= limit) {
                    var new_text = text.substr(0, limit);
                    $(this).html(new_text);
                }
            });
        });
    </script>
@endsection

resources/views/pages/rates/discountrates.blade.php
@extends('layouts.backend')

@section('meta-title', 'HostelPro - Discount Settings')

@php
$seasonId = null;
@endphp

@section('page-id', 'rates')
@section('content')
    @include('includes.ratessidebar')
    @if (count($seasonrates) == 0)
        <div id="content-wrapper" class="m-t-md">
            <p>Please Fill Season Rates Data</p>
        </div>
    @elseif(count($roomtypes) == 0)
        <div id="content-wrapper" class="m-t-md">
            <p>No Rooms found/p>
        </div>
    @else
    <div id="content-wrapper" class="m-t-md">
        {!! Form::open() !!}
        <div class="row seasonRates form-group">
            <ul class="nav nav-tabs">
                @foreach($seasonrates as $key => $seasonrate)
                    <li class="{{ ($key == 0) ? 'active' : '' }}" data-seasonId="{{$seasonrate->id}}">
                        <a href="">{{ $seasonrate->name }}<br><span class="small">{{ $seasonrate->getFormattedStartDate() }}
                                - {{ $seasonrate->getFormattedEndDate() }}</span></a>
                        @php
                            if(is_null($seasonId))
                            {
                                $seasonId = $seasonrate->id;
                            }
                        @endphp
                    </li>
                @endforeach
            </ul>
        </div>
        <div class="row form-group">
            <div class="col-xs-2">
                <select id="rooms" name="rooms" class="form-control">
                    @foreach($roomtypes as $room)
                        <option value="{{ $room['id'] }}">{{ $room['name'] }}</option>
                    @endforeach
                </select>
            </div>
        </div>
        <div class="row form-group">
            <div class="col-xs-2">
                Early Bird Discount
            </div>
            <div class="col-xs-2">
                <input class="form-control discount-text" type="text" placeholder="Discount %" id="earlyBirdPercent"
                       name="earlyBirdPercent"
                       value="@isset($currentDiscount) {{$currentDiscount->earlybird_discount}} @endisset"/>
            </div>
            <div class="col-xs-2">
                <input class="form-control discount-text" type="text" placeholder="Days in Advance" id="earlyBirdDays"
                       name="earlyBirdDays"
                       value="@isset($currentDiscount) {{$currentDiscount->earlybird_days}} @endisset"
                />
            </div>
        </div>
        <div class="row form-group">
            <div class="col-xs-2">
                Last Minute Discount
            </div>
            <div class="col-xs-2">
                <input class="form-control discount-text" type="text" placeholder="Discount %" id="lastMinutePercent"
                       name="lastMinutePercent"
                       value="@isset($currentDiscount) {{$currentDiscount->lastminute_discount}} @endisset"
                />
            </div>
            <div class="col-xs-2">
                <input class="form-control discount-text" type="text" placeholder="Days in Advance" id="lastMinuteHours"
                       name="lastMinuteHours"
                       value="@isset($currentDiscount) {{$currentDiscount->lastminute_days}} @endisset"
                />
            </div>
        </div>
        <div class="row form-group">
            <div class="col-xs-2">
                Progressive Pricing
            </div>
            <div class="col-xs-2">
                <input class="form-control discount-text" type="text" placeholder="Low Price" id="progressiveLowPrice"
                       name="progressiveLowPrice"
                       value="@isset($currentDiscount) {{$currentDiscount->progressive_low_price}} @endisset"
                />
            </div>
            <div class="col-xs-2">
                <input class="form-control discount-text" type="text" placeholder="High Price" id="progressiveHighPrice"
                       name="progressiveHighPrice"
                       value="@isset($currentDiscount) {{$currentDiscount->progressive_high_price}} @endisset"
                />
            </div>
        </div>
        <input type="hidden" id="seasonId" name="seasonId" value="{{$seasonId}}"/>
        <input type="hidden" id="discountRateId" name="discountRateId"
               value="@isset($currentDiscount) {{$currentDiscount->id}} @endisset"/>
        <p>
            <button class="btn m-b-xs btn-sm btn-success btn-addon" type="submit"><i class="fa fa-check"></i>Save
            </button>

        </p>
        {!! Form::close() !!}
        @endif
    </div>
@endsection
@section('footer')
    @parent
    <script type="text/javascript">
        $(document).ready(function (event) {
            $('.seasonRates').on('click', '.nav-tabs li', function (event) {
                event.preventDefault();
                $('.nav-tabs li').removeClass('active');
                $(this).addClass('active');

                var seasonid = $(this).data('seasonid');
                $('#seasonId').val(seasonid);

                $(this).closest('.seasonRates').find('.tab-pane').removeClass('active').eq($(this).index()).addClass('active');

                changeDiscountData();
            });

            $( "#rooms" ).on('change', function(e){
                changeDiscountData();
            });

            function changeDiscountData(){
                var data = $( "form" ).first().serializeArray();

                $.post('{{ route('settings.discount.find') }}', data,
                        function(res){
                            if(res.discountRate)
                            {
                                var obj = JSON.parse(res.discountRate);

                                $('#earlyBirdPercent').val(obj.earlybird_discount);
                                $('#earlyBirdDays').val(obj.earlybird_days);
                                $('#lastMinutePercent').val(obj.lastminute_discount);
                                $('#lastMinuteHours').val(obj.lastminute_days);
                                $('#progressiveLowPrice').val(obj.progressive_low_price);
                                $('#progressiveHighPrice').val(obj.progressive_high_price);

                                $('#discountRateId').val(obj.id);
                            }
                            else
                            {
                                $("input.discount-text:text").val("");
                                $('#discountRateId').val('');
                            }
                        }
                );
            }

            $('.btn-success').on('click', function(e){
                e.preventDefault();
                saveDiscountRateData();
            });


            function saveDiscountRateData() {
                var data = $( "form" ).first().serializeArray();
                $.ajax({
                    type: "POST",
                    url: '{{ route('settings.discount.save') }}',
                    data: data,
                    success: function (res) {
                        var id = res.id;

                        if(id)
                        {
                            $('#discountRateId').val(id);
                        }

                        var msg = res.message;
                        createSuccessModal(msg+". MyAllocator users please allow a few minutes for this to reach booking channels.");
                    }
                });
            }
        });
    </script>
@endsection