routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Auth::routes();

Route::get('/', 'WelcomeController@index');

Route::get('home', 'HomeController@index');
Route::post('home', ['as' => 'landingpage.contact', 'uses' => 'WelcomeController@sendContactForm']);

Route::group(array(), function() {
	#Authentication
	Route::get('/login', ['as' => 'login', 'uses' => 'SessionsController@create']);
	Route::get('/logout', ['as' => 'logout', 'uses' => 'SessionsController@destroy']);
	Route::resource('sessions', 'SessionsController', ['only' => ['create', 'store', 'destroy']]);
	Route::get('/changeActiveHostel/{id}', ['as' => 'changeactivehostel', 'uses' => 'SessionsController@changeActiveHostel']);

	#Registration
	Route::get('/register', ['as' => 'register', 'uses' => 'RegistrationController@create']);
	Route::post('/getTimezonesbyCountryID', ['as' => 'getTimezonesbyCountryID', 'uses' => 'RegistrationController@getTimezonesbyCountryID']);
	Route::resource('registration', 'RegistrationController', ['only' => ['create', 'store']]);

	#MyAllocatorCallback
	Route::post('/myallocator_callback', ['as' => 'myallocator.callback', 'uses' => 'MyAllocatorCallbackController@store']);

	#Uptime Page (This page is checked by pingdom and used to auto-switchover)
	Route::get('/uptimecheck', ['as' => 'uptimecheck', 'uses' => 'AjaxController@uptimeCheck']);

	#Testing Page
	Route::get('/testing', ['as' => 'testing', 'uses' => 'TestingController@index']);
	Route::post('/testing_add_guest', ['as' => 'testing.addGuest', 'uses' => 'TestingController@addGuest']);
	Route::post('/testing_add_booking', ['as' => 'testing.addBooking', 'uses' => 'TestingController@addBooking']);
	
});

Route::group(array('middleware' => 'auth'), function()
{
	#Calendar
	Route::get('/calendar', ['as' => 'calendar', 'uses' => 'CalendarController@create']);
	#legacy (can be removed soon):
	Route::get('/dashboard', ['as' => 'dashboard', 'uses' => 'CalendarController@create']);

	#Setup Steps
	Route::get('/setup', ['as' => 'setup.currentstep', 'uses' => 'SetupController@currentStep']);
	Route::get('/setup/next', ['as' => 'setup.nextstep', 'uses' => 'SetupController@nextStep']);
	Route::get('/setup/previous', ['as' => 'setup.previousstep', 'uses' => 'SetupController@previousStep']);

	#Calendar Test
	Route::get('/test', ['as' => 'testing.test', 'uses' => 'TestingController@testBookings']);
	Route::get('/test2', ['as' => 'testing.test2', 'uses' => 'TestingController@testPrivateBookingsImport']);

	#Ajax
	Route::post('/ajax/calendar', ['as' => 'ajax.calendar', 'uses' => 'AjaxController@calendar']);
	Route::get('/ajax/searchBookings', ['as' => 'ajax.searchBookings', 'uses' => 'AjaxController@searchBookings']);
	Route::post('/ajax/bookingDetails', ['as' => 'ajax.booking', 'uses' => 'AjaxController@bookingDetails']);
	Route::post('/ajax/getNotifications', ['as' => 'ajax.getnotifications', 'uses' => 'AjaxController@getNotifications']);

	Route::post('/savePayment', ['as' => 'savePayment', 'uses' => 'AjaxController@savePayment']);

	#Settings Page
	Route::get('/settings', ['as' => 'settings', 'uses' => 'SettingsController@index']);

	#MyAllocator callback setup
	Route::get('/set_myallocator_callback', ['as' => 'set.myallocator.callback', 'uses' => 'MyAllocatorCallbackController@setCallbackURL']);
	Route::get('/set_availability', ['as' => 'set.myallocator.availability', 'uses' => 'MyAllocatorCallbackController@setAvailability']);

	#Users Page
	Route::resource('users', 'UsersController', ['only' => ['index', 'show', 'store', 'destroy']]);

	#Guests Page
	Route::resource('guest', 'GuestController', ['only' => ['update']]);

	#Booking Page
	Route::resource('booking', 'BookingController', ['only' => ['show', 'update', 'edit', 'store', 'destroy']]);
	Route::post('/booking/{id}/updatelabel', ['as' => 'booking.updatelabel', 'uses' => 'BookingController@updateLabel']);
	Route::post('/booking/{id}/block', ['as' => 'booking.block', 'uses' => 'BookingController@block']);
	Route::post('/booking/{id}/unblock', ['as' => 'booking.unblock', 'uses' => 'BookingController@unblock']);
	Route::post('/booking/{id}/lock', ['as' => 'booking.lock', 'uses' => 'BookingController@lock']);
	Route::post('/booking/{id}/unlock', ['as' => 'booking.unlock', 'uses' => 'BookingController@unlock']);
	Route::post('/booking/{id}/noshow', ['as' => 'booking.noshow', 'uses' => 'BookingController@noshow']);
	Route::post('/booking/{id}/unallocate', ['as' => 'booking.unallocate', 'uses' => 'BookingController@unallocate']);
	Route::post('/booking/{id}/addStayToExistingTemp', ['as' => 'booking.addstaytoexistingtemp', 'uses' => 'BookingController@addStayToExistingTemp']);
	Route::post('/booking/{id}/movestay', ['as' => 'booking.movestay', 'uses' => 'BookingController@moveStay']);
	Route::post('/booking/createNewBookingAndBlock', ['as' => 'booking.createnewbookingandblock', 'uses' => 'BookingController@createNewBookingAndBlock']);
	Route::post('/booking/createNewBookingAndStay', ['as' => 'booking.createnewbookingandstay', 'uses' => 'BookingController@createNewBookingAndStay']);
	Route::resource('booking.note', 'NoteController', ['only' => ['index', 'store']]);

	#POS Page
	Route::resource('pos', 'POSController', ['only' => ['create']]);
	Route::get('/getProductsByCategoryId/{categoryId}', ['as' => 'pos.getProductsByCategoryId', 'uses' => 'POSController@getProductsByCategoryId']);
	Route::delete('/deleteItem/{id}', ['as' => 'pos.deleteitem', 'uses' => 'POSController@deleteItem']);
	Route::delete('/deletePayment/{id}', ['as' => 'pos.deletepayment', 'uses' => 'POSController@deletePayment']);

	#Invoice Page
	Route::get('/invoice/{id}/', ['as' => 'invoice.get', 'uses' => 'POSController@getInvoice']);

	#Expenses
	Route::resource('expense', 'ExpenseController', ['only' => ['index', 'store', 'destroy']]);

	#Reports
	Route::group(['prefix' => 'reports', 'as' => 'reports.'], function()
	{
		Route::get('/housekeeping', ['as' => 'housekeeping', 'uses' => 'ReportsController@houseKeeping']);
		Route::post('/housekeeping', ['as' => 'housekeepingdownload', 'uses' => 'ReportsController@houseKeeping']);
		Route::get('/paymentview', ['as' => 'paymentview', 'uses' => 'ReportsController@paymentView']);

		#DayView
		Route::get('/dayview', ['as' => 'dayview', 'uses' => 'ReportsController@dayView']);

		#Revenue
		Route::get('/revenue', ['as' => 'revenue', 'uses' => 'ReportsController@revenue']);

		#Dashboard
		Route::get('/dashboard', ['as' => 'dashboard', 'uses' => 'ReportsController@dashboard']);

		#Booking List
		Route::get('/bookinglist', ['as' => 'bookinglist', 'uses' => 'ReportsController@bookingList']);
		Route::get('/bookinglist/data', ['as' => 'bookinglistdata', 'uses' => 'ReportsController@bookingListData']);

		#PnL
		Route::get('/pnl', ['as' => 'profitandloss', 'uses' => 'ReportsController@pnl']);
		
		#M2m
		Route::get('/m2m', ['as' => 'month2month', 'uses' => 'ReportsController@m2m']);

		#Shift Reports
		Route::resource('shift', 'ShiftController', ['only' => ['index', 'create', 'store', 'show']]);

		#Shift Reports
		Route::resource('reviews', 'ReviewsController', ['only' => ['create', 'index', 'store', 'destroy']]);
	});

	#Settings
	Route::group(['prefix' => 'settings', 'as' => 'settings.'], function()
	{
		#Billing
		Route::resource('billing', 'BillingController', ['only' => ['create', 'store', 'destroy']]);

		#Room + Room Types Settings Page
		Route::get('/roomsOverview', ['as' => 'RoomsOverview', 'uses' => 'SettingsController@roomsOverview']);
		Route::resource('rooms', 'RoomsController', ['only' => ['edit', 'update', 'store', 'destroy']]);
		Route::post('/rooms/sort', ['as' => 'RoomsSort', 'uses' => 'RoomsController@sort']);
		Route::resource('roomtypes', 'RoomTypesController', ['only' => ['index', 'store', 'destroy']]);

		#POS Category + POS Product Settings Page
		Route::get('/POS', ['as' => 'posOverview', 'uses' => 'SettingsController@POSOverview']);
		Route::resource('POSCategory', 'POSCategoryController', ['only' => ['index', 'store', 'destroy', 'edit', 'update']]);
		Route::post('/POSCategory/sort', ['as' => 'POSCategory.sort', 'uses' => 'POSCategoryController@sort']);
		Route::resource('POSProduct', 'POSProductController', ['only' => ['index', 'store', 'destroy', 'edit', 'update']]);
		Route::post('/POSProduct/sort', ['as' => 'POSProduct.sort', 'uses' => 'POSProductController@sort']);

		#Money
		Route::resource('money', 'MoneyController', ['only' => ['create', 'store', 'destroy']]);

		#Money
		Route::get('/emailtest/{emailtype}', ['as' => 'email.test', 'uses' => 'EmailController@sendTestEmail']);
		Route::resource('email', 'EmailController', ['only' => ['create', 'store']]);

		#Payment Types
		Route::resource('paymenttypes', 'PaymentTypesController', ['only' => ['create', 'store', 'destroy']]);
		Route::post('/paymenttypes/sort', ['as' => 'paymenttypes.sort', 'uses' => 'PaymentTypesController@sort']);

		#Expenses
		Route::resource('expensecategory', 'ExpenseCategoryController', ['only' => ['create', 'store', 'destroy']]);

		#Rates
		Route::resource('rates', 'RatesController', ['only' => ['index', 'store', 'update', 'destroy']]);
		Route::get('/rates/competitor', ['as' => 'rates.competitor', 'uses' => 'RatesController@competitor']);
		Route::get('/rates/daily', ['as' => 'rates.daily', 'uses' => 'RatesController@daily']);
		Route::resource('competitor', 'CompetitorRatesController', ['only' => ['index', 'store', 'destroy']]);
		
		Route::post('/daily/store', ['as' => 'daily.store', 'uses' => 'DailyRatesController@store']);
		Route::post('/daily/get', ['as' => 'daily.get', 'uses' => 'DailyRatesController@get']);
		

resources/views/includes/colorizedifference.blade.php
@if ($value > 0)
  <span class="badge bg-success">{{ $value }}</span>
@elseif ($value < 0)
  <span class="badge bg-danger">{{ $value }}</span>
@else
  -
@endif

resources/views/includes/dashboardsidebar.blade.php
@if (1 == 2)
<aside id="dashboard-sidebar" data-spy="affix">
  <nav class="site-nav clearfix">

    <ul class="nav dashboardSidebar">

      <li id="openDashboardSidebar">
        <div class="row">
          <div class="col-sm-1">
            <i class="fa fa-2x fa-bars dashboard-sidebar-icon"></i>
          </div>
        </div>
      </li>

      <li id="bookingDetails" data-currentbookingid="">
        <div class="row">
            <div class="col-sm-1">
          <i class="fa fa-2x fa-money dashboard-sidebar-icon"></i>
          </div>
          <div class="col-sm-11">
          <h2 class="hidden dashboard-sidebar-text" id="bookingDetailsText">Cash Register</h2><i class="fa fa-caret-right icon hidden"></i>
          </div>
        </div>
       
      </li>
      <li id="bookingDetailsContainer" class="hidden sidebarContainer">
        <p>Please select a booking.</p>
      </li>

    </ul>

  </nav>
</aside>
@endif

resources/views/includes/datepicker.blade.php
<form class="form-inline">
  <div class="input-group dayview-selectdate">
              <span class="input-group-btn" id="dayViewMinusOneMonth">
                <button type="button" class="btn btn-default"><i class="fa fa-chevron-left"></i></button>
              </span>

    <div class="form-group">
      <input type="text" name="date" class="form-control input-md datepicker" value="{{ $date }}">
    </div>
              <span class="input-group-btn" id="dayViewAddOneMonth">
                <button type="button" class="btn btn-default"><i class="fa fa-chevron-right"></i></button>
              </span>
  </div>
  <button type="submit" class="btn btn-sm btn-info">View</button>
</form>

resources/views/includes/flashmessagediv.blade.php
@if (Session::has('flash_message'))
  <div class="row">
    <div class="col-lg-6 col-lg-offset-3 pt15">
      <div class="alert text-center {{ Session::get('alert-class', 'alert-info') }}">{!! Session::get('flash_message') !!}</div>
    </div>
  </div>
@endif

resources/views/includes/footer.blade.php
<footer id="site-foot" class="site-foot clearfix">
  <audio id="audioBell" controls preload="auto" class="hidden">
    <source src="{{ secure_asset('assets/audio/bell.mp3') }}" type="audio/mpeg">
  </audio>

  <p>© Copyright 2016 <strong>HostelPro</strong>, All rights reserved.

    Page generated in {!! sprintf('%0.3f',(microtime(true) - LARAVEL_START)) !!} seconds. Server:

    @if ($_SERVER['SERVER_ADDR'] == '192.168.10.10')
      Local
    @elseif ($_SERVER['SERVER_ADDR'] == '108.61.190.24')
      Staging (Frankfurt)
    @elseif ($_SERVER['SERVER_ADDR'] == '108.61.174.80')
      London
    @elseif ($_SERVER['SERVER_ADDR'] == '185.92.223.42')
      Amsterdam
    @elseif ($_SERVER['SERVER_ADDR'] == '45.63.50.167')
      Los Angeles
    @endif

  </p>
</footer>

resources/views/includes/modaldiv.blade.php
<div class="modal fade" id="modalDiv" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
    </div>
    <!-- /.modal-content -->
  </div>
  <!-- /.modal-dialog -->
</div> <!-- /.modal -->

resources/views/includes/ratessidebar.blade.php
<div id="sidebar-wrapper" class="m-t-sm">
    <ul class="sidebar-nav">

            <li class="{!! setActive( 'settings.rates.index') ? 'active' : '' !!}">
                <a href="{!! route('settings.rates.index') !!}">
                    <i class="fa fa-sun-o icon"></i>
                    <span>Season Rates</span>
                </a>
            </li>

            <li class="{!! setActive( 'settings.rates.competitor') ? 'active' : '' !!}">
                <a href="{!! route('settings.rates.competitor') !!}">
                    <i class="fa fa-bullseye icon"></i>
                    <span>Competitors</span>
                </a>
            </li>

            <li class="{!! setActive( 'settings.rates.daily') ? 'active' : '' !!}">
                <a href="{!! route('settings.rates.daily') !!}">
                    <i class="fa fa-gear icon"></i>
                     <span>Daily Rates</span>
                </a>
            </li>

            <li class="{!! setActive( 'settings.rates.discount') ? 'active' : '' !!}">
                <a href="{!! route('settings.rates.discount') !!}">
                    <i class="fa fa-dollar icon"></i>
                    <span>Discount Rates</span>
                </a>
            </li>

        </ul>

</div>

resources/views/includes/settingssidebar.blade.php
<div id="sidebar-wrapper" class="m-t-sm">
  <ul class="sidebar-nav">

        <li class="heading">Hostel</li>

        <li class="{!! setActive( 'settings.RoomsOverview') ? 'active' : '' !!}">
            <div class="pull-right text-success m-t-sm m-r-xs">
                <i class="fa fa-circle"></i>
            </div>
          <a href="{!! route('settings.RoomsOverview') !!}">
            <i class="fa fa-bed icon"></i>
            <span>Rooms</span>
          </a>
        </li>

        <li class="{!! setActive( 'settings.posOverview') ? 'active' : '' !!}">
            <div class="pull-right text-success m-t-sm m-r-xs">
                <i class="fa fa-circle"></i>
            </div>
          <a href="{!! route('settings.posOverview') !!}">
            <i class="fa fa-list-alt icon"></i>
            <span>POS</span>
          </a>
        </li>

        {{--<li>--}}
          {{--<a href="">--}}
            {{--<i class="fa fa-globe icon"></i>--}}
            {{--<span>Location</span>--}}
          {{--</a>--}}
        {{--</li>--}}

        <li class="{!! setActive( 'settings.paymenttypes.create') ? 'active' : '' !!}">
            <div class="pull-right text-success m-t-sm m-r-xs">
                <i class="fa fa-circle"></i>
            </div>
          <a href="{!! route('settings.paymenttypes.create') !!}">
            <i class="fa fa-money icon"></i>
            <span>Payment Types</span>
          </a>
        </li>

        <li class="{!! setActive( 'settings.money.create') ? 'active' : '' !!}">
            <div class="pull-right text-success m-t-sm m-r-xs">
                <i class="fa fa-circle"></i>
            </div>
          <a href="{!! route('settings.money.create') !!}">
            <i class="fa fa-euro icon"></i>
            <span>Currency/Money</span>
          </a>
        </li>

      <li class="{!! setActive( 'settings.email.create') ? 'active' : '' !!}">
          @if (Auth::user()->currenthostel->email)
              <div class="pull-right text-success m-t-sm m-r-xs">
                  <i class="fa fa-circle"></i>
              </div>
              @else
              <div class="pull-right text-muted m-t-sm m-r-xs">
                  <i class="fa fa-circle"></i>
              </div>
              @endif
          <a href="{!! route('settings.email.create') !!}">
              <i class="fa fa-envelope icon"></i>
              <span>Email</span>
          </a>
      </li>

        <li class="heading">Reports</li>

        <li class="{!! setActive( 'settings.expense.create') ? 'active' : '' !!}">
            <div class="pull-right text-success m-t-sm m-r-xs">
                <i class="fa fa-circle"></i>
            </div>
          <a href="{!! route('settings.expensecategory.create') !!}">
            <i class="fa fa-cogs icon"></i>
            <span>Expenses</span>
          </a>
        </li>

      <li class="{!! setActive( 'settings.competitor.index') ? 'active' : '' !!}">
          @if (Auth::user()->currenthostel->reviewURLs->count() > 0)
              <div class="pull-right text-success m-t-sm m-r-xs">
                  <i class="fa fa-circle"></i>
              </div>
          @else
              <div class="pull-right text-muted m-t-sm m-r-xs">
                  <i class="fa fa-circle"></i>
              </div>
          @endif
          <a href="{!! route('reports.reviews.create') !!}">
              <i class="fa fa-comments icon"></i>
              <span>Reviews</span>
          </a>
      </li>

        <li class="heading">Rates</li>

        <li class="{!! setActive( 'settings.competitor.index') ? 'active' : '' !!}">
            @if (Auth::user()->currenthostel->competitorURLs->count() > 0)
                <div class="pull-right text-success m-t-sm m-r-xs">
                    <i class="fa fa-circle"></i>
                </div>
            @else
                <div class="pull-right text-muted m-t-sm m-r-xs">
                    <i class="fa fa-circle"></i>
                </div>
            @endif
          <a href="{!! route('settings.competitor.index') !!}">
            <i class="fa fa-cogs icon"></i>
            <span>Competitors</span>
          </a>
        </li>

        <li class="heading">Channel Manager</li>

        <li class="{!! setActive( 'settings.myallocator.create') ? 'active' : '' !!}">
            @if (Auth::user()->currenthostel->myallocatorToken)
                <div class="pull-right text-success m-t-sm m-r-xs">
                    <i class="fa fa-circle"></i>
                </div>
            @else
                <div class="pull-right text-muted m-t-sm m-r-xs">
                    <i class="fa fa-circle"></i>
                </div>
            @endif
          <a href="{!! route('settings.myallocator.create') !!}">
            <i class="fa fa-cogs icon"></i>
            <span>MyAllocator</span>
          </a>
        </li>

      {{--<li class="heading">Billing</li>--}}

      {{--<li class="{!! setActive( 'settings.billing.create') ? 'active' : '' !!}">--}}
          {{--<a href="{!! route('settings.billing.create') !!}">--}}
              {{--<i class="fa fa-credit-card icon"></i>--}}
              {{--<span>Billing</span>--}}
          {{--</a>--}}
      {{--</li>--}}


        <li class="heading">
          <span>Accounts</span>
        </li>

        {{--<li>--}}
          {{--<a href="">--}}
            {{--<i class="fa fa-user icon"></i>--}}
            {{--<span>My Account</span>--}}
          {{--</a>--}}
        {{--</li>--}}

        <li class="{!! setActive( 'users.index') ? 'active' : '' !!}">
            <div class="pull-right text-success m-t-sm m-r-xs">
                <i class="fa fa-circle"></i>
            </div>
          <a href="{!! route('users.index') !!}">
            <i class="fa fa-users icon"></i>
            <span>Manage Users</span>
          </a>
        </li>

      </ul>
</div>

resources/views/includes/standardheader.blade.php
<div class="app-header navbar">
  <div class="navbar-header">
    <button class="pull-right visible-xs dk">
      <i class="glyphicon glyphicon-cog"></i>
    </button>
    <button class="pull-right visible-xs">
      <i class="glyphicon glyphicon-align-justify"></i>
    </button>
    <!-- brand -->
    <a href="#" class="navbar-brand text-lt">
      <span id="header-logo" class="hidden-folded m-l-xs">&nbsp; &nbsp; &nbsp; &nbsp;</span>
    </a>
    {{--<img src="{{ asset('assets/images/logo_white.png') }}" class="img-responsive">--}}
    <!-- / brand -->
  </div>
  <!-- / navbar header -->

  <!-- navbar collapse -->
  <div class="collapse pos-rlt navbar-collapse">

    <ul class="nav navbar-nav list-unstyled navbar-left">

      <li>
        <div id="sidebar-search">
          <select id="header-search" class="form-control no-border" style="width: 100%">

          </select>
        </div>
      </li>
      <li class="{!! setActive( 'calendar') ? 'active' : '' !!}">
        <a href="{!! route('calendar') !!}">
          <span class="text hidden-xs hidden-sm hidden-md">Bookings</span>
        </a>
      </li>
      <li class="{!! setActive( 'reports') ? 'active' : '' !!}">
        <a href="{!! route('reports.shift.create') !!}">
          <span class="text hidden-xs hidden-sm hidden-md">Reports</span>
        </a>
      </li>
      @if (Gate::allows('rates'))
      <li class="{!! setActive( 'settings.rates.index') ? 'active' : '' !!}">
        <a href="{!! route('settings.rates.index') !!}" class="auto">
          <span class="font-bold hidden-xs hidden-sm hidden-md">Rates</span>
        </a>
      </li>
        <li class="">
          <a href="http://help.hostelprofessional.com" target="_blank">
            <span class="text">Help</span>
          </a>
        </li>
      @endif
      @if (1 == 2)
      <li class="{!! Request::segment(1) == 'testing' ? 'active' : '' !!}">
        <a href="{!! route('testing') !!}">
          <i class="fa fa-flask icon"></i>
          <span class="text">Testing</span>
        </a>
      </li>
      @endif
    </ul>

    <!-- nabar right -->
    <ul class="nav navbar-nav navbar-right" id="navbar-right">

      <li id="bookingDetails" class="dropdown">
        <div class="dropdown-toggle">
          <i class="fa fa-money"></i>
        </div>
            <div id="bookingDetailsContainer" class="dropdown-menu">
              <h3 class="text-center">Please select a booking</h3>
      </li>

      <li id="notificationsContainer" class="dropdown">

        @include('includes.notifications')

      </li>

      <li id="alertsContainer" class="dropdown">

        @include('includes.alerts')

      </li>

      <li id="settingsContainer" class="dropdown btn-group">
        <div class="dropdown-toggle clear">
          {{--<span class="thumb-sm avatar pull-right m-t-n-sm m-b-n-sm m-l-sm">--}}
                {{--<img src="{!! secure_asset('assets/images/default.png', array(), true) !!}" alt="...">--}}
                {{--<i class="on md b-white bottom"></i>--}}
              {{--</span>--}}
          <i class="fa fa-user icon"></i>&nbsp;
            <span class="hidden-sm hidden-md underline-dashed">{{ Auth::user()->firstname }}</span>
          {{--<b class="caret"></b>--}}
        </div>
        <!-- dropdown -->
        <ul class="dropdown-menu" role="menu">

          @if (1 == 2)
          <li>
            <a href=""><i class="fa fa-user icon"></i><span>&nbsp; User Settings</span></a>
          </li>
          <li class="divider"></li>
          @endif

          @can('hostel_settings')
          <li class="{!! Request::segment(1) == 'settings' ? 'active' : '' !!}">
            <a href="{!! route('settings') !!}">
              <i class="fa fa-cog icon"></i>
              <span class="text">&nbsp; Hostel Settings</span>
            </a>
          </li>
            @endcan

          <li class="divider"></li>
            <li>
              <a href="{!! route('register') !!}"><i class="fa fa-plus icon"></i><span>&nbsp; Add Hostel</span></a>
            </li>

            @if (count(Auth::user()->hostelArrayList()) > 1)
            @foreach(Auth::user()->hostelArrayList() as $hostel_id => $hostel_name)
              <li>
                <a href="{!! route('changeactivehostel', $hostel_id) !!}"><i class="fa fa-bed icon"></i><span>&nbsp; {{ $hostel_name }}</span></a>
              </li>
            @endforeach
              <li class="divider"></li>
            @endif

          <li>
            <a href="{!! route('logout') !!}"><i class="fa fa-sign-out icon"></i><span>&nbsp; Logout</span></a>
          </li>
        </ul>

        <!-- / dropdown -->

      </li>


    </ul>
    <!-- / navbar right -->

  </div>
  <!-- / navbar collapse -->
</div>