routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Auth::routes();

Route::get('/', 'WelcomeController@index');

Route::get('home', 'HomeController@index');
Route::post('home', ['as' => 'landingpage.contact', 'uses' => 'WelcomeController@sendContactForm']);

Route::group(array(), function() {
	#Authentication
	Route::get('/login', ['as' => 'login', 'uses' => 'SessionsController@create']);
	Route::get('/logout', ['as' => 'logout', 'uses' => 'SessionsController@destroy']);
	Route::resource('sessions', 'SessionsController', ['only' => ['create', 'store', 'destroy']]);
	Route::get('/changeActiveHostel/{id}', ['as' => 'changeactivehostel', 'uses' => 'SessionsController@changeActiveHostel']);

	#Registration
	Route::get('/register', ['as' => 'register', 'uses' => 'RegistrationController@create']);
	Route::post('/getTimezonesbyCountryID', ['as' => 'getTimezonesbyCountryID', 'uses' => 'RegistrationController@getTimezonesbyCountryID']);
	Route::resource('registration', 'RegistrationController', ['only' => ['create', 'store']]);

	#MyAllocatorCallback
	Route::post('/myallocator_callback', ['as' => 'myallocator.callback', 'uses' => 'MyAllocatorCallbackController@store']);

	#Uptime Page (This page is checked by pingdom and used to auto-switchover)
	Route::get('/uptimecheck', ['as' => 'uptimecheck', 'uses' => 'AjaxController@uptimeCheck']);

	#Testing Page
	Route::get('/testing', ['as' => 'testing', 'uses' => 'TestingController@index']);
	Route::post('/testing_add_guest', ['as' => 'testing.addGuest', 'uses' => 'TestingController@addGuest']);
	Route::post('/testing_add_booking', ['as' => 'testing.addBooking', 'uses' => 'TestingController@addBooking']);
	
});

Route::group(array('middleware' => 'auth'), function()
{
	#Calendar
	Route::get('/calendar', ['as' => 'calendar', 'uses' => 'CalendarController@create']);
	#legacy (can be removed soon):
	Route::get('/dashboard', ['as' => 'dashboard', 'uses' => 'CalendarController@create']);

	#Setup Steps
	Route::get('/setup', ['as' => 'setup.currentstep', 'uses' => 'SetupController@currentStep']);
	Route::get('/setup/next', ['as' => 'setup.nextstep', 'uses' => 'SetupController@nextStep']);
	Route::get('/setup/previous', ['as' => 'setup.previousstep', 'uses' => 'SetupController@previousStep']);

	#Calendar Test
	Route::get('/test', ['as' => 'testing.test', 'uses' => 'TestingController@testBookings']);
	Route::get('/test2', ['as' => 'testing.test2', 'uses' => 'TestingController@testPrivateBookingsImport']);

	#Ajax
	Route::post('/ajax/calendar', ['as' => 'ajax.calendar', 'uses' => 'AjaxController@calendar']);
	Route::get('/ajax/searchBookings', ['as' => 'ajax.searchBookings', 'uses' => 'AjaxController@searchBookings']);
	Route::post('/ajax/bookingDetails', ['as' => 'ajax.booking', 'uses' => 'AjaxController@bookingDetails']);
	Route::post('/ajax/getNotifications', ['as' => 'ajax.getnotifications', 'uses' => 'AjaxController@getNotifications']);

	Route::post('/savePayment', ['as' => 'savePayment', 'uses' => 'AjaxController@savePayment']);

	#Settings Page
	Route::get('/settings', ['as' => 'settings', 'uses' => 'SettingsController@index']);

	#MyAllocator callback setup
	Route::get('/set_myallocator_callback', ['as' => 'set.myallocator.callback', 'uses' => 'MyAllocatorCallbackController@setCallbackURL']);
	Route::get('/set_availability', ['as' => 'set.myallocator.availability', 'uses' => 'MyAllocatorCallbackController@setAvailability']);

	#Users Page
	Route::resource('users', 'UsersController', ['only' => ['index', 'show', 'store', 'destroy']]);

	#Guests Page
	Route::resource('guest', 'GuestController', ['only' => ['update']]);

	#Booking Page
	Route::resource('booking', 'BookingController', ['only' => ['show', 'update', 'edit', 'store', 'destroy']]);
	Route::post('/booking/{id}/updatelabel', ['as' => 'booking.updatelabel', 'uses' => 'BookingController@updateLabel']);
	Route::post('/booking/{id}/block', ['as' => 'booking.block', 'uses' => 'BookingController@block']);
	Route::post('/booking/{id}/unblock', ['as' => 'booking.unblock', 'uses' => 'BookingController@unblock']);
	Route::post('/booking/{id}/lock', ['as' => 'booking.lock', 'uses' => 'BookingController@lock']);
	Route::post('/booking/{id}/unlock', ['as' => 'booking.unlock', 'uses' => 'BookingController@unlock']);
	Route::post('/booking/{id}/noshow', ['as' => 'booking.noshow', 'uses' => 'BookingController@noshow']);
	Route::post('/booking/{id}/unallocate', ['as' => 'booking.unallocate', 'uses' => 'BookingController@unallocate']);
	Route::post('/booking/{id}/addStayToExistingTemp', ['as' => 'booking.addstaytoexistingtemp', 'uses' => 'BookingController@addStayToExistingTemp']);
	Route::post('/booking/{id}/movestay', ['as' => 'booking.movestay', 'uses' => 'BookingController@moveStay']);
	Route::post('/booking/createNewBookingAndBlock', ['as' => 'booking.createnewbookingandblock', 'uses' => 'BookingController@createNewBookingAndBlock']);
	Route::post('/booking/createNewBookingAndStay', ['as' => 'booking.createnewbookingandstay', 'uses' => 'BookingController@createNewBookingAndStay']);
	Route::resource('booking.note', 'NoteController', ['only' => ['index', 'store']]);

	#POS Page
	Route::resource('pos', 'POSController', ['only' => ['create']]);
	Route::get('/getProductsByCategoryId/{categoryId}', ['as' => 'pos.getProductsByCategoryId', 'uses' => 'POSController@getProductsByCategoryId']);
	Route::delete('/deleteItem/{id}', ['as' => 'pos.deleteitem', 'uses' => 'POSController@deleteItem']);
	Route::delete('/deletePayment/{id}', ['as' => 'pos.deletepayment', 'uses' => 'POSController@deletePayment']);

	#Invoice Page
	Route::get('/invoice/{id}/', ['as' => 'invoice.get', 'uses' => 'POSController@getInvoice']);

	#Expenses
	Route::resource('expense', 'ExpenseController', ['only' => ['index', 'store', 'destroy']]);

	#Reports
	Route::group(['prefix' => 'reports', 'as' => 'reports.'], function()
	{
		Route::get('/housekeeping', ['as' => 'housekeeping', 'uses' => 'ReportsController@houseKeeping']);
		Route::post('/housekeeping', ['as' => 'housekeepingdownload', 'uses' => 'ReportsController@houseKeeping']);
		Route::get('/paymentview', ['as' => 'paymentview', 'uses' => 'ReportsController@paymentView']);

		#DayView
		Route::get('/dayview', ['as' => 'dayview', 'uses' => 'ReportsController@dayView']);

		#Revenue
		Route::get('/revenue', ['as' => 'revenue', 'uses' => 'ReportsController@revenue']);

		#Dashboard
		Route::get('/dashboard', ['as' => 'dashboard', 'uses' => 'ReportsController@dashboard']);

		#Booking List
		Route::get('/bookinglist', ['as' => 'bookinglist', 'uses' => 'ReportsController@bookingList']);
		Route::get('/bookinglist/data', ['as' => 'bookinglistdata', 'uses' => 'ReportsController@bookingListData']);

		#PnL
		Route::get('/pnl', ['as' => 'profitandloss', 'uses' => 'ReportsController@pnl']);
		
		#M2m
		Route::get('/m2m', ['as' => 'month2month', 'uses' => 'ReportsController@m2m']);

		#Shift Reports
		Route::resource('shift', 'ShiftController', ['only' => ['index', 'create', 'store', 'show']]);

		#Shift Reports
		Route::resource('reviews', 'ReviewsController', ['only' => ['create', 'index', 'store', 'destroy']]);
	});

	#Settings
	Route::group(['prefix' => 'settings', 'as' => 'settings.'], function()
	{
		#Billing
		Route::resource('billing', 'BillingController', ['only' => ['create', 'store', 'destroy']]);

		#Room + Room Types Settings Page
		Route::get('/roomsOverview', ['as' => 'RoomsOverview', 'uses' => 'SettingsController@roomsOverview']);
		Route::resource('rooms', 'RoomsController', ['only' => ['edit', 'update', 'store', 'destroy']]);
		Route::post('/rooms/sort', ['as' => 'RoomsSort', 'uses' => 'RoomsController@sort']);
		Route::resource('roomtypes', 'RoomTypesController', ['only' => ['index', 'store', 'destroy']]);

		#POS Category + POS Product Settings Page
		Route::get('/POS', ['as' => 'posOverview', 'uses' => 'SettingsController@POSOverview']);
		Route::resource('POSCategory', 'POSCategoryController', ['only' => ['index', 'store', 'destroy', 'edit', 'update']]);
		Route::post('/POSCategory/sort', ['as' => 'POSCategory.sort', 'uses' => 'POSCategoryController@sort']);
		Route::resource('POSProduct', 'POSProductController', ['only' => ['index', 'store', 'destroy', 'edit', 'update']]);
		Route::post('/POSProduct/sort', ['as' => 'POSProduct.sort', 'uses' => 'POSProductController@sort']);

		#Money
		Route::resource('money', 'MoneyController', ['only' => ['create', 'store', 'destroy']]);

		#Money
		Route::get('/emailtest/{emailtype}', ['as' => 'email.test', 'uses' => 'EmailController@sendTestEmail']);
		Route::resource('email', 'EmailController', ['only' => ['create', 'store']]);

		#Payment Types
		Route::resource('paymenttypes', 'PaymentTypesController', ['only' => ['create', 'store', 'destroy']]);
		Route::post('/paymenttypes/sort', ['as' => 'paymenttypes.sort', 'uses' => 'PaymentTypesController@sort']);

		#Expenses
		Route::resource('expensecategory', 'ExpenseCategoryController', ['only' => ['create', 'store', 'destroy']]);

		#Rates
		Route::resource('rates', 'RatesController', ['only' => ['index', 'store', 'update', 'destroy']]);
		Route::get('/rates/competitor', ['as' => 'rates.competitor', 'uses' => 'RatesController@competitor']);
		Route::get('/rates/daily', ['as' => 'rates.daily', 'uses' => 'RatesController@daily']);
		Route::resource('competitor', 'CompetitorRatesController', ['only' => ['index', 'store', 'destroy']]);
		
		Route::post('/daily/store', ['as' => 'daily.store', 'uses' => 'DailyRatesController@store']);
		Route::post('/daily/get', ['as' => 'daily.get', 'uses' => 'DailyRatesController@get']);
		

resources/views/pages/contact.blade.php
<h1>Address</h1>
<p>PO Box 10451, Keaau, HI 96721</p>
<h1>Email</h1>
<p>jeremiah@hostelprofessional.com</p>
<h1>Phone</h1>
<p>+385 20 715 268</p>

resources/views/pages/expensecategories.blade.php
@extends('layouts.backend')

@section('meta-title', 'HostelPro - Settings - Expense Categories')

@section('page-id', 'settings')

@section('content')
    @include('includes.settingssidebar')

    <div id="content-wrapper" class="m-t-md">


        <div class="row">
            <div class="col-lg-6">
                <table class="table table-condensed category">
                    <thead>
                    <th width="50%">Name</th>
                    <th width="50%">Remove</th>
                    </thead>
                    <tbody>
                    @if (count($expenseCategories))
                        @include('partials.expensecategory')
                    @else
                        <tr id="nocategory">
                            <td>No categories have been added.</td>
                        </tr>
                    @endif
                    </tbody>
                </table>
                <p>
                    <button class="btn m-b-xs btn-sm btn-primary btn-addon" id="addcategory"><i class="fa fa-plus"></i>Add
                        Category
                    </button>
                </p>

            </div>
        </div>

    </div>
@endsection
@section('footer')
    @parent

    <script type="text/javascript">
        $(document).ready(function () {

            var newMoneyBlock = '<tr>' +
                    '<td class="v-middle"><input type="text" class="form-control categoryname" name="categoryname" placeholder="eg Utilities"> </td>' +
                    '<td>' +
                    '<button class="btn btn-sm btn-info saveExpense"><i class="fa fa-floppy-o"></i>&nbsp; Save</button>' +
                    '<button class="btn btn-sm btn-danger deleteRow"><i class="fa fa-trash-o"></i>&nbsp; Delete</button>' +
                    '</td>' +
                    '</tr>';

            $("#addcategory").click(function () {
                $(".category tbody").append(newMoneyBlock);
                $("#nocategory").addClass("hidden");
            });

            $(document).on('click', '.saveExpense', function () {
                var data = {};
                data.categoryname = $(this).parent().parent().find('.categoryname').val();
                //var $data = [$name, $roomtype, $gender, $capacity];
                //console.log( JSON.stringify(data) );
                saveItem('{!! route('settings.expensecategory.store') !!}', data, $(this));
            });

            $(document).on('click', '.deleteRow', function () {
                $(this).closest('tr').remove();
            });

            $(document).on('click', '.deleteExpense', function () {
                confirmDeletePopup('{!! route('settings.expensecategory.destroy', '') !!}', $(this).data("expenseid"), 'DELETE');
            });

            function confirmDeletePopup($type, $id, $requesttype) {
                noty({
                    text: 'Are you sure you want to delete this item?',
                    theme: 'relax',
                    layout: 'center',
                    modal: true,
                    animation: {
                        open: {height: 'toggle'}, // jQuery animate function property object
                        close: {height: 'toggle'}, // jQuery animate function property object
                        easing: 'swing', // easing
                        speed: 150 // opening & closing animation speed
                    },
                    buttons: [
                        {
                            addClass: 'btn btn-success', text: 'Ok', onClick: function ($noty) {
                            $noty.close();
                            deleteItem($type, $id, $requesttype);
                        }
                        },
                        {
                            addClass: 'btn btn-danger', text: 'Cancel', onClick: function ($noty) {
                            $noty.close();
                        }
                        }
                    ]
                });
            };

            function deleteItem($type, $id, $requesttype) {
                $.ajax({
                    url: $type + "/" + $id,
                    type: $requesttype,
                    success: function (response) {
                        $("table.category tbody").html(response);
                    },
                    error: function (xhr, ajaxOptions, thrownError) {
                        createErrorModal(xhr.responseText);
                    }
                });
            };

            function saveItem($type, $data, $row) {
                $.ajax({
                    url: $type,
                    type: 'POST',
                    data: $data,
                    success: function (response) {
                        $row.parent().parent().replaceWith(response);
                    },
                    error: function (xhr, ajaxOptions, thrownError) {
                        createErrorModal(xhr.responseText);
                    }
                });
            };


        });
    </script>
@endsection

resources/views/pages/money.blade.php
@extends('layouts.backend')

@section('meta-title', 'HostelPro - Settings - Money')

@section('page-id', 'settings')

@section('content')

  @include('includes.settingssidebar')

  <div id="content-wrapper" class="m-t-md">

            <div class="row">

              <div class="col-lg-6">
                <div class="panel panel-lined mb30">
                  <div class="panel-heading font-bold">Money List</div>
                  <div class="panel-body">
                    <table class="table table-condensed money">
                      <thead>
                      <th width="50%">Amount</th>
                      <th width="50%">Remove</th>
                      </thead>
                      <tbody>
                      @if (count($money))
                        @include('partials.money')
                      @else
                        <tr id="nomoney">
                          <td>No money amounts have been added.</td>
                        </tr>
                      @endif
                      </tbody>
                    </table>
                    <p>
                      <button class="btn m-b-xs btn-sm btn-primary btn-addon" id="addmoney"><i class="fa fa-plus"></i>Add Amount</button>
                    </p>
                  </div>
                </div>
              </div>

            </div>

          </div>
@endsection
@section('footer')
  @parent

  <script type="text/javascript">
    $(document).ready(function () {

      var newMoneyBlock = '<tr>' +
              '<td class="v-middle"><input type="number" class="form-control amount" name="amount" placeholder="0.00" min="0" step="0.01"> </td>' +
              '<td>' +
              '<button class="btn btn-sm btn-info saveMoney"><i class="fa fa-floppy-o"></i>&nbsp; Save</button>' +
              '<button class="btn btn-sm btn-danger deleteRow"><i class="fa fa-trash-o"></i>&nbsp; Delete</button>' +
              '</td>' +
              '</tr>';

      $("#addmoney").click(function () {
        $(".money tbody").append(newMoneyBlock);
        $("#nomoney").addClass("hidden");
      });

      $(document).on('click', '.saveMoney', function () {
        var data = {};
        data.amount = $(this).parent().parent().find('.amount').val();
        //var $data = [$name, $roomtype, $gender, $capacity];
        //console.log( JSON.stringify(data) );
        saveItem('{!! route('settings.money.store') !!}', data, $(this));
      });

      $(document).on('click', '.deleteRow', function () {
        $(this).closest('tr').remove();
      });

      $(document).on('click', '.deleteMoney', function () {
        confirmDeletePopup('{!! route('settings.money.destroy', '') !!}', $(this).data("moneyid"), 'DELETE');
      });

      function confirmDeletePopup($type, $id, $requesttype) {
        noty({
          text: 'Are you sure you want to delete this item?',
          theme: 'relax',
          layout: 'center',
          modal: true,
          animation: {
            open: {height: 'toggle'}, // jQuery animate function property object
            close: {height: 'toggle'}, // jQuery animate function property object
            easing: 'swing', // easing
            speed: 150 // opening & closing animation speed
          },
          buttons: [
            {
              addClass: 'btn btn-success', text: 'Ok', onClick: function ($noty) {
              $noty.close();
              deleteItem($type, $id, $requesttype);
            }
            },
            {
              addClass: 'btn btn-danger', text: 'Cancel', onClick: function ($noty) {
              $noty.close();
            }
            }
          ]
        });
      };

      function deleteItem($type, $id, $requesttype) {
        $.ajax({
          url: $type + "/" + $id,
          type: $requesttype,
          success: function (response) {
            $("table.money").html(response);
          },
          error: function (xhr, ajaxOptions, thrownError) {
            createErrorModal(xhr.responseText);
          }
        });
      };

      function saveItem($type, $data, $row) {
        $.ajax({
          url: $type,
          type: 'POST',
          data: $data,
          success: function (response) {
            $row.parent().parent().replaceWith(response);
          },
          error: function (xhr, ajaxOptions, thrownError) {
            createErrorModal(xhr.responseText);
          }
        });
      };


    });
  </script>


@endsection

resources/views/pages/paymenttypes.blade.php
@extends('layouts.backend')

@section('meta-title', 'HostelPro - Settings - Money')

@section('page-id', 'settings')

@section('content')

    @include('includes.settingssidebar')

    <div id="content-wrapper" class="m-t-md">

                        <div class="row">

                            <div class="col-sm-12">
                                <div class="panel panel-lined mb30">
                                    <div class="panel-heading font-bold">Payment Types List</div>
                                    <div class="panel-body">
                                        <table class="table table-condensed paymenttype">
                                            <thead>
                                            <th>Payment Type</th>
                                            <th>Kept in Till</th>
                                            <th>Remove</th>
                                            </thead>
                                            <tbody id="paymentTypeTable">
                                            @if (count($payment_types))
                                                @include('partials.paymenttype')
                                            @else
                                                <tr id="nopaymenttype">
                                                    <td>No payment types have been added.</td>
                                                </tr>
                                            @endif
                                            </tbody>
                                        </table>
                                        <p>
                                            <button class="btn m-b-xs btn-sm btn-primary btn-addon" id="addpaymenttype"><i class="fa fa-plus"></i>Add Payment Type</button>
                                        </p>
                                    </div>
                                </div>
                            </div>

                        </div>

                    </div>
@endsection
@section('footer')
    @parent

    <script type="text/javascript">
        $(document).ready(function () {

            var newPaymentTypeBlock = '<tr>' +
                    '<td class="v-middle"><input type="text" class="form-control" name="name" placeholder="eg Cash Payment" required> </td>' +
                    '<td class="v-middle">{!! Form::select("kept_in_till", [true => 'Yes', false => 'No'], 1, array("class" => "form-control")) !!}</td>' +
                    '<td>' +
                    '<button class="btn btn-sm btn-info savePaymentType"><i class="fa fa-floppy-o"></i>&nbsp; Save</button>' +
                    '<button class="btn btn-sm btn-danger deleteRow"><i class="fa fa-trash-o"></i>&nbsp; Delete</button>' +
                    '</td>' +
                    '</tr>';

            $("#addpaymenttype").click(function () {
                $(".paymenttype tbody").append(newPaymentTypeBlock);
                $("#nopaymenttype").addClass("hidden");
            });

            $(document).on('click', '.savePaymentType', function () {
                var data = {};
                data.name = $(this).parent().parent().find('[name="name"]').val();
                data.keptintill = $(this).parent().parent().find('[name="kept_in_till"]').val();
                saveItem('{!! route('settings.paymenttypes.store') !!}', data, $(this));
            });

            $(document).on('click', '.deleteRow', function () {
                $(this).closest('tr').remove();
            });

            $(document).on('click', '.deletePaymentType', function () {
                confirmDeletePopup('{!! route('settings.paymenttypes.destroy', '') !!}', $(this).data("id"), 'DELETE');
            });

            $('#paymentTypeTable').sortable({
                axis: 'y',
                update: function (event, ui) {
                    var data = $(this).sortable('serialize');
                    data += '&_token={{ csrf_token() }}';

                    console.log(data);
                    $.ajax({
                        url: '{{ route('settings.paymenttypes.sort') }}',
                        type: 'POST',
                        data: data
                    });

                }
            });

            function confirmDeletePopup($type, $id, $requesttype) {
                noty({
                    text: 'Are you sure you want to delete this item?',
                    theme: 'relax',
                    layout: 'center',
                    modal: true,
                    animation: {
                        open: {height: 'toggle'}, // jQuery animate function property object
                        close: {height: 'toggle'}, // jQuery animate function property object
                        easing: 'swing', // easing
                        speed: 150 // opening & closing animation speed
                    },
                    buttons: [
                        {
                            addClass: 'btn btn-success', text: 'Ok', onClick: function ($noty) {
                            $noty.close();
                            deleteItem($type, $id, $requesttype);
                        }
                        },
                        {
                            addClass: 'btn btn-danger', text: 'Cancel', onClick: function ($noty) {
                            $noty.close();
                        }
                        }
                    ]
                });
            }

            function deleteItem($type, $id, $requesttype) {
                $.ajax({
                    url: $type + "/" + $id,
                    type: $requesttype,
                    success: function (response) {
                        $("table.paymenttype").html(response);
                    },
                    error: function (xhr, ajaxOptions, thrownError) {
                        createErrorModal(xhr.responseText);
                    }
                });
            }

            function saveItem($type, $data, $row) {
                $.ajax({
                    url: $type,
                    type: 'POST',
                    data: $data,
                    success: function (response) {
                        $row.parent().parent().replaceWith(response);
                    },
                    error: function (xhr, ajaxOptions, thrownError) {
                        createErrorModal(xhr.responseText);
                    }
                });
            }


        });
    </script>


@endsection

resources/views/pages/settings.blade.php
@extends('layouts.backend')

@section('meta-title', 'HostelPro - Settings')

@section('content')

  @include('includes.standardheader')



  <div class="main-container clearfix" id="settings">
    @include('includes.settingssidebar')


    @include('includes.footer')
  </div>
@stop

resources/views/pages/shiftreportindex.blade.php
@extends('layouts.backend')

@section('meta-title', 'HostelPro - Shift Reports')

@section('page-id', 'reports')

@section('content')


    @include('includes.reportssidebar')

    <div id="content-wrapper" class="m-t-md">

        <table class="table table-condensed table-hover">
            <thead>
            <tr>
                <th>View</th>
                <th>Status</th>
                <th>Created By</th>
                <th>$ Diff</th>
                <th>Created At</th>
                <th>Completed At</th>
                <th>$ Start</th>
                <th>$ End</th>
            </tr>
            </thead>
            <tbody>
            @if ($reports)
                @foreach ($reports as $report)
                    <tr>
                        <td>
                            <a href="{{ route('reports.shift.show', ['id' => $report->id]) }}">
                                <button class="btn btn-default btn-xs">View Report</button>
                            </a>
                        </td>
                        @if ($report->isCompleted())
                            <td><span class="label bg-success">Completed</span></td>
                        @else
                            <td><span class="label bg-danger">Not Completed</span></td>
                        @endif
                        <td>{{ $report->user->fullName() }}</td>
                        @if ($report->isCompleted())
                            <td>{{ \App\HostelPro\Models\MoneyHelper::convertCentsToDollars(($report->totalDifference() + $report->expenses->sum('price')) - ($report->payments->sum('total'))) }}</td>
                        @else
                            <td></td>
                        @endif
                        <td>{{ $report->start_time }}</td>
                        @if ($report->isCompleted())
                            <td>{{ $report->end_time }}</td>
                        @else
                            <td></td>
                        @endif
                        <td>{{ $report->startTotal() }}</td>
                        <td>{{ $report->endTotal() }}</td>
                    </tr>
                @endforeach

            @else
                <tr>
                    <td colspan="5">There are currently no shift reports in the system.</td>
                </tr>
            @endif

            </tbody>
        </table>
    </div>
@endsection